<main >
	
	 <div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
	  
              <span class="card-title">
              	<div class="row">
              		<div class="col s6">
              			 <div data-activates="slide-out" class="chip button-collapse" style="cursor: pointer;">
		              		<i class="fa fa-bars" aria-hidden="true"></i>
						    <?php echo $lang_listados[1]//Listas?>				    
						  </div>
              		</div>
              		<div class="col s6 right-align">
              			
              			<i style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_personalizados[44]//Ver tutorial ?>" class="fa fa-play tooltipped" aria-hidden="true" onclick="playVideoTutorial()"></i>

              		</div>
              	</div>
              </span>
				

					<div class="row">	
						<div id="div_videoTutorial" style="display: none;" class="col s12 center-align">
								<h5><?php echo $lang_personalizados[27] //Tutorial personalizados?></h5>
							 <video id="videoTutorial_personalizados" class="responsive-video" height="600" width="600"  controls>
							 	
							 	<?php 
							 		
							 		if(is_file("Public/videos/tutoriales/".$idiomaIndex."/listados/listados.mp4")){
							 	
								?>
										<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/listados/listados.mp4" type="video/mp4">
								<?php	
							 		}else{
							 	?>
							 			<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/FueraServicio/fueraServicio.mp4" type="video/mp4">
							 	<?php	
							 		}
							 	?>
							 	
							    
							  </video>
							  <h6 class="center-align">
							  	<a class="waves-effect red darken-1 btn" onclick="cerrarVideoTutorial()"><i class="fa fa-stop" aria-hidden="left"></i> <?php echo $lang_personalizados[28] //Cerrar vídeo?></a>
							  </h6>
						</div><!-- Fin div col video-->
					</div>


				<div class="row">
					
					<div class="col s12 m12 l12">
						
						<ul class="collection with-header">
							
							<li class="collection-header">
								<h4 id="tituloLi" class="center-align" ><?php echo $lang_categoriasProductos[0]//Categorías de los productos?>
									
									<?php
							    		//saber si tiene permisos para adicionar categorias
										if(in_array("104", $_SESSION['permisos_usuario'] )){
									?>
									
						  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_categoriasProductos[1]//Nueva categoría?>" onclick="mostrarFormNuevaCategoria()">
						  				<i class="material-icons">add</i>
						  			</a>
						  			
						  			<?php
										}
									?>
						  			
						  		</h4>						  		
						  		<br />
						  		<?php
							    		//saber si tiene permisos para editar categorias
										if(in_array("103", $_SESSION['permisos_usuario'] )){
									?>
						  		<div id="hidden_editarCategoria" style="display: none;">						  			
						  			
						  			<div class="row">
				                      	<div class="col s12 m12 l12">
				                      		<h4 class="center-align"><?php echo $lang_categoriasProductos[2]//Editar categoría?></h4>
				                      	</div>
				                      </div>
						  			<div class="row">
						  				<form id="form_editarCategoria" name="form_editarCategoria" action="" method="post" >
						  					<input type="hidden" id="idEditarCategoria" name="idEditarCategoria" value="" />
							  				<input type="hidden" id="replicaNombre" name="replicaNombre" value="" />
							  				<div class="input-field col s12 m8 l8">
							  					<input type="text" id="editarNombreCategoria" name="editarNombreCategoria" value="" length="100" maxlength="100"/>
							  					<label id="label_editarNombreCategoria" for="editarNombreCategoria"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_categoriasProductos[3]//Nombre categoría?></label>
							  				</div>
						  				</form>
						  				<div class="input-field col s12 m4 l4 center-align">					  					
						  						<a class="waves-effect red darken-1 btn" onclick="cancelarEdicionCategoria()" ><?php echo $lang_botones[5]//Cancelar?></a>		
						  						<a class="waves-effect waves-light btn" onclick="comprobarEdicionCategoria()" ><?php echo $lang_botones[4]//Editar?></a>				  									  					
						  				</div>
						  			</div>
						  			
						  		</div>
						  		<?php
						  		
						  				}//fin if permiso editar categoria
								
							    		//saber si tiene permisos para adicionar categorias
										if(in_array("104", $_SESSION['permisos_usuario'] )){
									?>
						  		<div id="hidden_NuevaCategoria" style="display: none;">
						  			
						  			<div class="row">
						  				<form class="col s12 m12 l12" id="form_nuevaCategoria" name="form_nuevaCategoria" action="" method="post">
						  					
						                    <input type="hidden" id="envioNuevaCategoria" name="envioNuevaCategoria"  value="envio"/>
						                    
						                    <div class="row">
                          
						                      
						                      <div class="input-field col s12 m8 l8">						                            
						                            <input id="nombreCategoria" name="nombreCategoria" type="text" class="validate" length="100" maxlength="100">
						                            <label id="label_nombreCategoria" for="nombreCategoria"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_categoriasProductos[4]//Nombre de la nueva categoría?></label> 
						                      </div> 
						                      
							                  
							                  <div class="input-field col s12 m4 l4 right-align">
							                  	<a class="waves-effect red darken-1 btn" onclick="cancelarGuardadoNuevaCategoria()"><?php echo $lang_botones[5]//Cancelar?></a>
							                    <a class="waves-effect waves-light btn" onclick="validarGuardadoNuevaCategoria()"><?php echo $lang_botones[2]//Guardar?></a>
							                  </div>
						                  </div><!-- fin row-->
						  					
						  					
						  				</form>
						  			</div><!-- Fin row-->
						  		</div><!-- fin Div oculto para formulario del nueva categoria-->
						  		<?php
						  			}//fin permiso crear nueva categoria
						  		?>
						  		
							</li>
							
						</ul>
						
					</div>				
					
				</div><!-- Fin row-->
				
				
				<div class="row">
					<div class="input-field col s10 m3 l3">
						<i class="fa fa-search prefix" aria-hidden="true"></i>
						<input placeholder="<?php echo $lang_categoriasProductos[5]//Buscar categoría (Escribe y selecciona)?>" id="buscarCategoria" type="text" class="validate" onkeypress="buscarCategoriaListados()" >
						<input type="hidden" id="idCategoriaBuscada" value="" />
					</div>
					<div class="input-field col s2 m2 l2">
						<i id="btnCancelarBusqueda" class="fa fa-times-circle fa-3x" aria-hidden="true" style="cursor: pointer; display: none;" onclick="cerrarBusquedaCategoria()"></i>
					</div>
				</div>
				
				
				<div class="row">
					
					<div class="col s12 m12 l12">
						<span id="spanActivar" style="display: none;"><?php echo $lang_categoriasProductos[6]//Activar categoría?></span>
						<span id="spanDesactivar" style="display: none;"><?php echo $lang_categoriasProductos[7]//Desactivar categoría?></span>
						
							<div id="resultadoCategoriasAjax">
								
							</div><!-- Fin para el resultado de las categorías ajax-->
							
							<div id="resultadoCategorias">
								<table class="bordered highlight centered responsive-table">
									
									<thead>
										<tr>
											<th><?php echo $lang_categoriasProductos[8]//Categoría?></th>
											<th><?php echo $lang_general[12]//Estado?></th>
										</tr>
									</thead>
									
									<tbody>
										
										<?php									
											foreach ($listadoCategorias as $listadoCategorias1) {
												
												if($listadoCategorias1['estado'] == 'A'){																																																			//Desactivar categoria
													$btn = '<span id="spanB_'.$listadoCategorias1['idCategoria'].'"> <a id="'.$listadoCategorias1['idCategoria'].'" class="waves-effect waves-light btn tooltipped" onclick="desactivarCategoria(this.id)"  data-position="right" data-delay="50" data-tooltip="'.$lang_categoriasProductos[7].'" ><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}else{																																																											//Activar categoria
													$btn = '<span id="spanB_'.$listadoCategorias1['idCategoria'].'"> <a id="'.$listadoCategorias1['idCategoria'].'" class="waves-effect red darken-1 btn tooltipped" onclick="activarCategoria(this.id)" data-position="right" data-delay="50" data-tooltip="'.$lang_categoriasProductos[6].'"><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}
												
												$parametros = "'".$listadoCategorias1['idCategoria']."','".$listadoCategorias1['nombre']."'";
										?>
										
											<tr style="cursor: pointer;">
												<td <?php if(in_array("103", $_SESSION['permisos_usuario'] )){ ?> onclick="editarCategoria(<?php echo $parametros?>)" <?php } ?> ><?php echo $listadoCategorias1['nombre']?></td>
												<td>
													<?php echo $btn ?>											
												</td>
											</tr>											
												
										<?php		
											}//fin foreach								
										?>
										
										
										
									</tbody>
									
									
								</table>
								
							</div><!-- Fin div para los resultados de las categorias-->	
						
					</div>
					
				</div><!-- Fin row-->
				
				

			 </div>
          </div>
        </div>
      </div>


	<!-- paginacion -->
		<footer class="page-footer white">
					<?php
					
					// render the pagination links
					$pagination->render();
					
					?>
		</footer>	
	<!-- fin paginacion -->	
	
</main>