<footer class="page-footer black">
  <div class="container white-text">
   
        © 2017 Copyright NanuVet
        <a class="white-text right" href="https://www.facebook.com/nanuvet/" target="_blank" style="padding-left:10px"><i class="fa fa-facebook fa-lg"></i> Facebook</a>
        <a class="white-text right" href="https://twitter.com/nanuvet" target="_blank"  style="padding-left:10px"><i class="fa fa-twitter fa-lg"></i> Twitter @nanuvet</a>
        <a class="white-text right" href="javascript:void(0)"><i class="fa fa-whatsapp fa-lg"></i> (57) 315 723 45 46</a>
        
        <div class="row">
        		&nbsp;
        </div>
    
  </div>
</footer>