<div class="section" id="section4" style="background-image: url(Public/img/fondos/lightpaperfibers.png)">

	<h1 style="margin-bottom: -50px;"><?php echo $lang_index[22]//Modulos?></h1>

	<div class="slide">
		
		<h3 class="center-align"><?php echo $lang_index[23]//Historia clínica?></h3>
		<p><?php echo $lang_index[24]//Controla todo el proceso de salud de tus pacientes?></p>
		
		<div class="row">
			
			<div class="col s1">
				&nbsp;
			</div>
			
			<div class="col s10 center-align">
				<div class="row">
					<div class="col s6">				
    					<img class="responsive-img" src="Public/img/modulos/historiaClinica.png">        
					</div>
					<div class="col s6">				
    					<img class="responsive-img" src="Public/img/modulos/historiaClinica2.png">        
					</div>
				</div>
			</div>
			
			<div class="col s1">
				&nbsp;
			</div>
			
			
		</div>
			
	</div><!-- Fin slide-->



	<div class="slide">
		
		<h3 class="center-align"><?php echo $lang_index[25]//Agenda?></h3>
		<p><?php echo $lang_index[26]//Gestiona horarios y citas de los usuarios?></p>
		
		<div class="row">
			
			<div class="col s1">
				&nbsp;
			</div>
			
			<div class="col s10 center-align">
				<div class="row">
					<div class="col s6">				
		    			<img class="responsive-img" src="Public/img/modulos/agenda1.png">        
					</div>
					
					<div class="col s6">
						<img class="responsive-img" src="Public/img/modulos/agenda2.png">
					</div>
				</div>
			</div>
			
			<div class="col s1">
				&nbsp;
			</div>
			
			
		</div>
			
	</div><!-- Fin slide-->




	<div class="slide">
		
		<h3 class="center-align"><?php echo $lang_index[27]//Inventario?></h3>
		<p><?php echo $lang_index[28]//Lleva el control de tu inventario, incluso en distintas sucursales?></p>
		
		<div class="row">
			
			<div class="col s1">
				&nbsp;
			</div>
			
			<div class="col s10 center-align">
				<div class="row">
					<div class="col s6">				
		    			<img class="responsive-img" src="Public/img/modulos/inventario1.png">        
					</div>
					
					<div class="col s6">
						<img class="responsive-img" src="Public/img/modulos/inventario2.png">
					</div>
				</div>
			</div>
			
			<div class="col s1">
				&nbsp;
			</div>
			
			
		</div>
			
	</div><!-- Fin slide-->



	<div class="slide">
		
		<h3 class="center-align"><?php echo $lang_index[29]//Facturación?></h3>
		<p><?php echo $lang_index[30]//No perderás dinero con el control de tus productos y servicios?></p>
		
		<div class="row">
			
			<div class="col s1">
				&nbsp;
			</div>
			
			<div class="col s10 center-align">
				<div class="row">
					<div class="col s6">				
		    			<img class="responsive-img" src="Public/img/modulos/facturacion1.png">        
					</div>
					
					<div class="col s6">
						<img class="responsive-img" src="Public/img/modulos/facturacion2.png">
					</div>
				</div>
			</div>
			
			<div class="col s1">
				&nbsp;
			</div>
			
			
		</div>
			
	</div><!-- Fin slide-->
	
	<div class="slide">
		<h2 class="center-align"><?php echo $lang_index[31] //Y mucho más...?></h2>
	</div>


</div><!-- Fin section-->