<div class="section" id="section6" style="background-image: url(Public/img/fondos/lightpaperfibers.png)">

	<div class="container">
	        
    	    <div class="row">
              <div class="col s12 m12 l12">
              	<div class="card">
                	<div class="card-content">
                		<span class="card-title"><?php echo $lang_index[37]//Contactanos?></span>
                	
                			<div class="row">
                				
                				<div class="input-field col s12 m6 l6">
                					<input id="contactoNombre" name="contactoNombre" type="text" class="validate" maxlength="100" length="100">
          							<label id="label_contactoNombre" for="contactoNombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;"><?php echo $lang_index[38]//Tu nombre?><span class="red-text text-darken-2">*</span></label>
                				</div>
                				
                				<div class="input-field col s12 m6 l6">
                					<input id="contactoEmail" name="contactoEmail" type="text" class="validate" maxlength="200" length="200">
          							<label id="label_contactoEmail" for="contactoEmail" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;">E-mail<span class="red-text text-darken-2">*</span></label>
                				</div>
                				
                			</div>
                			
                			<div class="row">
                				<div class="input-field col s12">
                					<textarea id="contactoTexto" name="contactoTexto" class="materialize-textarea" maxlength="500" length="500"></textarea>
          							<label id="label_contactoTexto" for="contactoTexto" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;"><?php echo $lang_index[39]//Mensaje?><span class="red-text text-darken-2">*</span></label>
                				</div>
                			</div>
                			
                			<div class="row">
                				<div class="col s12 center-align">                					
									<a class="waves-effect waves-light btn" onclick="enviarMensajeContactanos()" ><?php echo $lang_index[40]//Enviar mensaje?></a>
                				</div>
                			</div>
                			
                			<div class="row">
                				<div class="col s12">
                					<span style="display: none;" id="mensajeEnvioMensaje" class="green-text text-darken-2"><?php echo $lang_index[41]//Gracias por contactarnos!. De ser necesario responderemos en la mayor brevedad posible.?></span>
                				</div>
                			</div>
                			
                			<div class="row">
                				<div class="col s12 right-align">
                					<span><i class="fa fa-whatsapp"></i> (57) 315 723 45 46</span>
                				</div>
                			</div>
                	
                	
 					</div>
 				</div>
              </div>
            </div><!-- fin row-->
        
 </div><!-- Fin container-->
	

</div><!-- Fin section-->