<div class="section" id="section1" style="background-image: url(Public/img/fondos/lightpaperfibers.png)">

        <br />
        <br />
        <br />
        <h4 class="center-align"><?php echo $lang_index[10]//Un amigo para cuidar a tus amigos?></h4>
    
            <div class="row">
                <div class="col s12 m12 l12">
                        <p class="flow-text" id="s1_descripcion" >
                            <?php echo $lang_index[11]//NanuVet es un software de historias clínicas veterinarias.?>
                            <br /><?php echo $lang_index[12]//Elaborado para ser la mejor herramienta para los veterinarios y ayudar a los propietarios con el cuidado de sus mascotas o animales.?> 
                        </p>
                </div>
            </div><!-- Fin row-->
            
            <div class="row">
                
                <div class="col s12 m6 l6">
                    <h4><?php echo $lang_index[13]//Misión?></h4>
                    <blockquote>
                        <p class="flow-text">
                            <?php echo $lang_index[14]//Brindar un software intuitivo, confiable e innovador. Que sirva como una gran herramienta tanto para propietarios de mascotas o animales, como para profesionales e instituciones veterinarias?>
                        </p>
                    </blockquote>
                </div>
                
                <div class="col s12 m6 l6">
                    <h4><?php echo $lang_index[15]//Visión?></h4>
                    <blockquote>
                        <p class="flow-text">
                           <?php echo $lang_index[16]//En el año 2018 ser el referente a nivel mundial en el sector veterinario en la prestación de software como servicio, destacado por la calidad, atención e innovación.?>
                        </p>
                    </blockquote>
                </div>
         
                
            </div><!-- Fin row-->
    
   

</div><!-- Fin section1-->