	<div id="fullpage">

        <div class="section" id="section0">
        	
        	<video autoplay loop muted id="myVideo">
			 	<source src="Public/videos/<?php echo $video?>.mp4" type="video/mp4"/>
			</video>
			
			<div class="layer">
				
				<div class="container" style="margin-top: -2%; opacity: 0.8;" >
	                           
	                <div class="row">
	                        <div class="col s12 m12 l12" >
	                           <div class="card grey lighten-5 hoverable">  
	                           
	                               <div class="card-content black-text" style="background-image: url(Public/img/fondos/bright_squares.png)" >
	                                
	                                   <div class="row valign-wrapper" >
	                                   	
	                                        <div class="col s12 m12 l12 center-align">
	                                            <h2 id="titulo" class="center-align">
	                                                <ul class="texts">
	                                                    <li data-in-effect="bounceIn" data-out-effect="bounceOut" data-out-sequence="true"><?php echo $lang_index[0]//Amigable?></li>   
	                                                    <li data-in-effect="bounceIn" data-out-effect="bounceOut" data-out-sequence="true"><?php echo $lang_index[1]//Ágil?></li>
	                                                    <li data-in-effect="bounceIn" data-out-effect="bounceOut" data-out-sequence="true"><?php echo $lang_index[2]//Confiable?></li>
	                                                    <li data-in-effect="bounceIn" data-out-effect="bounceOut" data-out-sequence="true"><?php echo $lang_index[3]//Innovador?></li>
	                                                </ul>
	                                            </h2>
	                                        </div>
	                                        
	                                    </div><!-- Fin row-->
	                                    
	                                    <div class="row">
	                                    	
	                                    	<div class="col s12 m4 l4 valign center-align input-field">
	                                          <a class="waves-effect waves-light btn-large tooltipped" href="#precios" data-menuanchor="precios" data-position="top" data-delay="50" data-tooltip="<?php echo $lang_index[7]//Conoce los planes para adquirir el software?>"><i class="fa fa-usd"></i> <?php echo $lang_index[4]//Precios?></a>
	                                        </div>
	                                        
	                                        <div class="col s12 m4 l4 valign center-align input-field">
	                                          <a class="waves-effect waves-light btn-large tooltipped" href="#tumascota" data-menuanchor="tumascota" data-position="top" data-delay="50" data-tooltip="<?php echo $lang_index[8]//Consulta la historia clínica de tu mascota. Es gratis!?>"><i class="fa fa-paw"></i> <?php echo $lang_index[5]//Tu mascota?></a>
	                                        </div>
	                                        
	                                        <div class="col s12 m4 l4 valign center-align input-field">
	                                          <a class="waves-effect waves-light btn-large tooltipped" href="#login" data-menuanchor="tumascota" data-position="top" data-delay="50" data-tooltip="<?php echo $lang_index[9]//Ingresa al software?>"><i class="fa fa-lock"></i> <?php echo $lang_index[6]//Iniciar sesión?></a>
	                                        </div>
	                                    	
	                                    </div>
	                                
	                                </div><!-- Fin contenedor del card-->
	                                
	                           </div><!-- Fin card-->
	                       </div><!-- fin col-->
	               
	               </div><!-- Fin row-->
	               
	           </div><!-- Fin container-->
	           
			</div><!-- Fin layer-->
			
        </div><!-- Fin section 0-->