<main>
	
	 <div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
              <span class="card-title">             	
              	
              	<div class="row">
              		<div class="col s6">
              			<?php echo $lang_menu[17]//usuarios?>
              		</div>
              		<div class="col s6 right-align">                			            			
              			<i style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_general[19]//Ver tutorial?>" class="fa fa-play tooltipped" aria-hidden="true" onclick="playVideoTutorial()"></i>
              		</div>
              	</div>    
              	          	
              </span>


              <div class="row">	
				<div id="div_videoTutorial" style="display: none;" class="col s12 center-align">
						<h5>Video-tutorial</h5>
					 <video id="videoTutorial_personalizados" class="responsive-video" height="600" width="600" controls>					    
					  
					  			<?php 
							 		
							 		if(is_file("Public/videos/tutoriales/".$idiomaIndex."/usuarios/usuarios.mp4")){
							 	
								?>
										<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/usuarios/usuarios.mp4" type="video/mp4">
								<?php	
							 		}else{
							 	?>
							 			<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/FueraServicio/fueraServicio.mp4" type="video/mp4">
							 	<?php	
							 		}
							 	?>
					  
					  </video>
					  <h6 class="center-align">
					  	<a class="waves-effect red darken-1 btn" onclick="cerrarVideoTutorial()"><i class="fa fa-stop" aria-hidden="left"></i> <?php echo $lang_general[18] //Cerrar video?></a>
					  </h6>
				</div><!-- Fin div col video-->
			</div>

					<div class="row">
					
						<div class="col s12 m12 l12">
							
							<ul class="collection with-header">
							
								<li class="collection-header">
									<h4 id="tituloLi" class="center-align" ><?php echo  $lang_usuarios[0]//Usuarios de la cuenta?>
										
									<?php
							    		//saber si tiene permisos para adicionar usuarios
										if(in_array("11", $_SESSION['permisos_usuario'] )){
									?>	
										
							  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_usuarios[1]//Nuevo usuario?>" onclick="mostrarFormNuevoUsuario()">
							  				<i class="material-icons">add</i>
							  			</a>
							  			
							  		<?php
										}//fin if para adicionar usuarios
									?>
							  			
							  		</h4>
							  		
							  		<br />
							  		
							  		<!-- Div para formulario de nuevo usuario-->
							  		<?php
							    		//saber si tiene permisos para adicionar usuarios
										if(in_array("11", $_SESSION['permisos_usuario'] )){
									?>	
							  			<div id="hidden_formNuevoUsuario" style="display: none;">
							  				
							  				<div class="row">
							  					<form class="col s12 m12 l12" id="form_nuevoUsuario" name="form_nuevoUsuario" action="" method="post">
							  						
							  						<input type="hidden" id="hidden_envioFormNuevo" name="hidden_envioFormNuevo" value="enviar" />	
							  						
							  						 <div class="row">
								                      	<div class="col s12 m12 l12">
								                      		<h4 class="center-align"><?php echo $lang_usuarios[1]//Nuevo usuario?></h4>
								                      	</div>
								                      </div>
								                      
								                      <div class="row">
								                      	
								                      	  <div class="input-field col s12 m4 l4">
								                              <input id="identificacion" name="identificacion" type="text" class="validate" length="30" maxlength="30">
								                              <label id="label_identificacion" for="identificacion" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[1]//Identificación?></label>
								                          </div>
								                          
								                           <div class="input-field col s12 m4 l4">
								                              <input id="nombre" name="nombre" type="text" class="validate" length="100" maxlength="100">
								                              <label id="label_nombre" for="nombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[2]//Nombres?></label>
								                          </div>
								                          
								                           <div class="input-field col s12 m4 l4">
								                              <input id="apellido" name="apellido" type="text" class="validate" length="100" maxlength="100">
								                              <label id="label_apellido" for="apellido" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[3]//Apellidos?></label>
								                          </div>
							  						
							  						  </div><!-- fin row-->	
							  						  
							  						  <div class="row">
							  						  	
								                          
								                          <div class="input-field col s12 m2 l2">
								                              <input id="telefono" name="telefono" type="text" class="validate" length="20" maxlength="20">
								                              <label id="label_telefono" for="telefono" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[0]//Teléfono?></label>
								                          </div>
								                          
								                          <div class="input-field col s12 m2 l2">
								                              <input id="celular" name="celular" type="text" class="validate" length="20" maxlength="20">
								                              <label id="label_celular" for="celular" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[2]//Celular?></label>
								                          </div>
								                          
								                          <div class="input-field col s12 m4 l4">
								                              <input id="direccion" name="direccion" type="text" class="validate" length="50" maxlength="50">
								                              <label id="label_direccion" for="direccion" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[3]//Dirección?></label>
								                          </div>
							  						  	
							  						  	  <div class="input-field col s12 m4 l4">
								                              <input id="email" name="email" type="text" class="validate" length="50" maxlength="50">
								                              <label id="label_email" for="email" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" >E-mail</label>
								                          </div>
							  						  	
							  						  </div><!-- fin row-->	
							  						  
							  						  <div class="row">
							  						  	
							  						  	<div class="input-field col s12 m4 l4" style="margin-top: 0;">
								                               <div class="input-field col s12">
															    <select  id="idLicenciaParaUsuario" name="idLicenciaParaUsuario">
															      <option value="0" disabled selected><?php echo $lang_usuarios[2]//Seleccionar licencia?></option>
															      
															      <?php
															      	foreach ($listadoLicenciasDisponibles as $listadoLicenciasDisponibles1) {
																  ?>
																  		<option value="<?php echo $listadoLicenciasDisponibles1['idLicencia']?>"><?php echo $listadoLicenciasDisponibles1['fechaFin']?></option>
																  <?php																		  
																	  }
															      ?>
															      
															    </select>
															    <label><?php echo $lang_usuarios[3]//Vincular usuario con una licencia?></label>
															  </div>
								                          </div>
							  						  	
								                          								                          								                          
								                          <div class="input-field col s12 m4 l4" style="margin-top: 0;">
								                               <div class="input-field col s12">
															    <select  id="sucursalesUsuario" name="sucursalesUsuario[]" multiple>
															      <option value="0" disabled selected><?php echo $lang_usuarios[4]//Seleccionar sucursales?></option>
															      
															      <?php
															      	foreach ($listadoSucursales as $listadoSucursales1) {
																  ?>
																  		<option value="<?php echo $listadoSucursales1['idSucursal']?>"><?php echo $listadoSucursales1['nombre']?></option>
																  <?php																		  
																	  }
															      ?>
															      
															    </select>
															    <label><?php echo $lang_usuarios[5]//Elija las sucursales para el usuario?></label>
															  </div>
								                          </div>
								                          
								                          <div class="col s12 m4 l4">
								                          	
								                          	<div class="row">
								                          		<div class="input-field col s12 m6 l6">
								                          			<p class="center-align">
																      <input type="checkbox" id="usarAgenda" name="usarAgenda" />
																      <label for="usarAgenda"><?php echo $lang_usuarios[6]//Utilizar agenda?></label>
																    </p>
								                          		</div>
								                          		
								                          		<div class="input-field col s12 m6 l6">
								                          			<div class="switch">
															    <label>
															      <?php echo $lang_general[10]//Inactivo?>
															      <input type="checkbox" id="estado" name="estado" checked="checked" >
															      <span class="lever"></span>
															      <?php echo $lang_general[9]//Activo?>
															    </label>
															  </div>
								                          		</div>
								                          		
								                          	</div>
								                          	
									                          									                                
								                          </div>
							  						  	
							  						  </div><!-- fin row-->	
							  						  
							  						  <div class="row">
								                        <div class="input-field col s12 m12 l12 right-align">
								                        	<span id="spanErrorSucursal" style="display: none;" class="red-text text-darken-2"><?php echo $lang_usuarios[7]//Debe elegir almenos una sucursal para el usuario?></span>
								                          <a class="waves-effect red darken-1 btn" onclick="cancelarGuardadoUsuario()"><?php echo $lang_botones[5]//Cancelar?></a>
								                          <a class="waves-effect waves-light btn" onclick="validarGuardadoUsuario()"><?php echo $lang_botones[2]//Guardar?></a>
								                        </div>
								                      </div>
							  							
							  					</form><!-- Fin col-->
							  				</div><!-- Fin row-->
							  				
							  			</div>
							  		<?php
										}//fin if para adicionar usuarios
									?>
							  		<!-- Fin div para formulario de nuevo usuario-->
							  		
							  		
							  		<!-- Formulario para editar los datos d eun usuario-->
							  		
							  		<div id="form_hidden_editarUsuario" style="display: none;">
							  			
							  			<div class="row">
							  				<form class="col s12 m12 l12" id="form_editarUsuario" name="form_editarUsuario" action="" method="post">
													  			
										  			<input type="hidden" id="envioEditarUsuario" name="envioEditarUsuario" value="enviar" />
										  			
										  			<input type="hidden" id="idUsuario" name="idUsuario" value="" />	
							  						
							  						 <div class="row">
								                      	<div class="col s12 m12 l12">
								                      		<h4 class="center-align"><?php echo $lang_usuarios[8]//Editar usuario?></h4>
								                      	</div>
								                      </div>
								                      
								                      <div class="row">
								                      	
								                      	  <div class="input-field col s12 m4 l4">
								                              <input id="editer_identificacion" name="editer_identificacion" type="text" class="validate" length="30" maxlength="30" disabled>
								                              <label id="label_editer_identificacion" for="editer_identificacion" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[1]//Identificación?></label>
								                          </div>
								                          
								                           <div class="input-field col s12 m4 l4">
								                              <input id="editer_nombre" name="editer_nombre" type="text" class="validate" length="100" maxlength="100" disabled>
								                              <label id="label_editer_nombre" for="editer_nombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[2]//Nombres?></label>
								                          </div>
								                          
								                           <div class="input-field col s12 m4 l4">
								                              <input id="editer_apellido" name="editer_apellido" type="text" class="validate" length="100" maxlength="100" disabled>
								                              <label id="label_editer_apellido" for="editer_apellido" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[3]//Apellidos?></label>
								                          </div>
							  						
							  						  </div><!-- fin row-->	
							  						  
							  						  <div class="row">
							  						  	
								                          
								                          <div class="input-field col s12 m2 l2">
								                              <input id="editer_telefono" name="editer_telefono" type="text" class="validate" length="20" maxlength="20">
								                              <label id="label_editer_telefono" for="editer_telefono" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[0]//Teléfono?></label>
								                          </div>
								                          
								                          <div class="input-field col s12 m2 l2">
								                              <input id="editer_celular" name="editer_celular" type="text" class="validate" length="20" maxlength="20">
								                              <label id="label_editer_celular" for="editer_celular" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[2]//Celular?></label>
								                          </div>
								                          
								                          <div class="input-field col s12 m4 l4">
								                              <input id="editer_direccion" name="editer_direccion" type="text" class="validate" length="50" maxlength="50">
								                              <label id="label_editer_direccion" for="editer_direccion" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[3]//Dirección?></label>
								                          </div>
							  						  	
							  						  	  <div class="input-field col s12 m4 l4">
								                              <input id="editer_email" name="editer_email" type="text" class="validate" length="50" maxlength="50" disabled>
								                              <label id="label_editer_email" for="editer_email" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" >E-mail</label>
								                          </div>
							  						  	
							  						  </div><!-- fin row-->	
							  						  
							  						  <div class="row">							  						  	
								                          					
								                          
								                          <div class="col s12 m6 l6">
								                          	
								                          	<div class="row">
								                          		<div class="input-field col s12 m6 l6">
								                          			<p class="center-align">
																      <input type="checkbox" id="editer_usarAgenda" name="editer_usarAgenda" />
																      <label for="editer_usarAgenda"><?php echo $lang_usuarios[6]//Utilizar agenda?></label>
																    </p>
								                          		</div>
								                          		
								                          		<div class="input-field col s12 m6 l6">
								                          			<div class="switch">
															    <label>
															      <?php echo $lang_general[10]//Inactivo?>
															      <input <?php if(!in_array("13", $_SESSION['permisos_usuario'] )){ ?> disabled="disabled" <?php } ?>   type="checkbox" id="editer_estado" name="editer_estado" checked="checked" >
															      <span class="lever"></span>
															      <?php echo $lang_general[9]//Activo?>
															    </label>
															  </div>
								                          		</div>
								                          		
								                          	</div>
								                          	
									                          									                                
								                          </div>
							  						  	
								                        <div class="input-field col s12 m6 l6 right-align">								                        	
								                          <a class="waves-effect red darken-1 btn" onclick="cancelarEdicionUsuario()"><?php echo $lang_botones[5]//Cancelar?></a>
								                          <a class="waves-effect waves-light btn" onclick="validarEdicionUsuario()"><?php echo $lang_botones[4]//Editar?></a>
								                        </div>
								                      </div>
							  							
							  					</form><!-- Fin col-->
							  			</div>
							  			
							  			
							  			
							  		</div>
							  		
							  		<!-- Fin divFormulario para editar los datos d eun usuario-->
							  		
							  		
							  		
							  	</li>
							  	
							  	
							  	<?php
							  	
									foreach ($listadoUsuarios as $listadoUsuarios1) {
										
										$idUsuario 			= $listadoUsuarios1['idUsuario'];
										$identificacion 	= $listadoUsuarios1['identificacion'];
										$nombre 			= $listadoUsuarios1['nombre'];
										$apellido 			= $listadoUsuarios1['apellido'];
										$telefono 			= $listadoUsuarios1['telefono'];
										$celular 			= $listadoUsuarios1['celular'];
										$direccion 			= $listadoUsuarios1['direccion'];
										$email 				= $listadoUsuarios1['email'];
										$urlFoto 			= $listadoUsuarios1['urlFoto'];
										$agenda 			= $listadoUsuarios1['agenda'];
										$estado 			= $listadoUsuarios1['estado'];
										$idLicencia 		= $listadoUsuarios1['idLicencia'];
										
										
										if($idLicencia != "0"){
											//consultar la fecha final de la licencia
											$fechaFinalLicenciaUsuario = $objetoUsuarios->consultarFechaFinLicencia($idLicencia);
																	//Si, hasta
											$informacionLicencia = $lang_usuarios[9]." ".$fechaFinalLicenciaUsuario;
										}else{
											$informacionLicencia = "No";
										}
										
										if($urlFoto == ""){
											$rutaFoto =	"../Public/img/porDefectoClientes/bulding.png";
										}else{
											$rutaFoto =	"../Public/uploads/".$_SESSION['BDC_carpeta']."/img_usuarios/".$urlFoto;
										}
										

										$parametrosEditar = "'".$idUsuario."','".$identificacion."','".$nombre."','".$apellido."','".$telefono."','".$celular."','".$direccion."','".$email."','".$agenda."','".$estado."'";
										
								?>
										<li class="collection-item avatar <?php if($estado != 'A' ){?>grey lighten-1<?php } ?>" >
											<?php
										     	//validar si el paciente tiene foto (de lo contrario s emuestra una por defecto)
										     	if($listadoUsuarios1['urlFoto'] != ""){
										     ?>
										     		<img src="<?php echo "../Public/uploads/".$_SESSION['BDC_carpeta']."/img_usuarios/".$listadoUsuarios1['urlFoto']  ?>" alt="<?php echo $listadoUsuarios1['nombre']?>" class="responsive-img circle materialboxed" >
										     <?php
										     	}
										     ?>	
										     
										     <span class="title"><?php echo $listadoUsuarios1['nombre']." ".$listadoUsuarios1['apellido']?></span>
										     
										     <div class="row hoverable tooltipped" style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_nuevo[29]//Ver la información de ?><?php echo $listadoUsuarios1['nombre']?>" onclick="editarUsuario(<?php echo $parametrosEditar ?>)" >
							     	
										     	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_perfil[1]//Identificación?></strong></div>
										      	<div class="col s6 m1 l1"><?php echo $listadoUsuarios1['identificacion'] ?></div>					      	
										      	<div class="col s6 m1 l1" style="text-align: right;" ><strong>E-mail</strong></div>
										      	<div class="col s6 m2 l2"><?php echo $listadoUsuarios1['email']?></div>							      					      	
										      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_general[2]//Celular?></strong></div>
										      	<div class="col s6 m1 l1"><?php echo $listadoUsuarios1['celular']?></div>
										      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_usuarios[10]//Agenda?></strong></div>
										      	<div class="col s6 m1 l1"><?php echo $listadoUsuarios1['agenda'] ?> </div>
										      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_usuarios[11]//Licencia?></strong></div>
										      	<div class="col s6 m2 l2"><?php echo $informacionLicencia?></div>
										     	
										     </div><!-- Fin row -->
										     
										</li>										
								
								<?php		
									}//fin foreach								
								?>
						  	
						  	</ul>
							
						</div><!-- Fin col-->
					</div><!-- Fin row-->



			</div>
			
          </div>
        </div>
      </div>
	
	
</main>