<main>
<div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">              
              <div class="chip tooltipped" id="chip_propietario"  style="cursor: pointer;" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_nuevo[36]//Ver la información del propietario?>"  onclick="mostrarFormEditarPropietario()" ?>
              	<i class="fa fa-user" aria-hidden="true"></i>
			    <?php echo $informacionPropietario['identificacion']." -- ".$informacionPropietario['nombre']." ".$informacionPropietario['apellido'] ?>
			 
			  </div>
			  
			  <h6 class="center-align"> <span class="green-text text-darken-2" ><?php echo $lang_index[47]//Los cambios en la información se deben hacer desde la aplicación móvil, esto con el fin de que solo el propietario pueda modificar los datos.?></span></h6>
				<h6 class="center-align"> <span class="green-text text-darken-2" style="display: none;" ><?php echo $lang_index[48]//Click aquí para descargar la aplicación móvil?></span></h6>
			  
			  
			  
			 <!-- Div para ver la información del propietario-->			 
			 <div id="hideFormEditarpropietario" style="display: none; " >
						 		                  			              	
             
			              	 <div class="row">
			              	 	
						        <div class="input-field col s12 m4 l4">
						          <input disabled id="propietario_identificacion" name="propietario_identificacion" type="text" class="validate" length="30" maxlength="30" value="<?php echo $informacionPropietario['identificacion'] ?>">
						          <label id="label_propietario_identificacion" for="propietario_identificacion" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[1]//Identificación?></label>
						        </div>
						        
						        <div class="input-field col s12 m4 l4">
						          <input disabled id="propietario_nombre" name="propietario_nombre" type="text" class="validate" length="30" maxlength="30" value="<?php echo $informacionPropietario['nombre'] ?>">
						          <label id="label_propietario_nombre" for="propietario_nombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[2]//Nombres?></label>
						        </div>
						        
						        <div class="input-field col s12 m4 l4">
						          <input disabled id="propietario_apellido" name="propietario_apellido" type="text" class="validate" length="30" maxlength="30" value="<?php echo $informacionPropietario['apellido'] ?>">
						          <label id="label_propietario_apellido" for="propietario_apellido" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_perfil[3]//Apellidos?></label>
						        </div>
						        
						      </div><!-- Fin row-->
						      
						      <div class="row">
						      	
						      	<div class="input-field col s12 m4 l4">
						          <input disabled id="propietario_telefono" name="propietario_telefono" type="text" class="validate" length="20" maxlength="20" value="<?php echo $informacionPropietario['telefono'] ?>">
						          <label id="label_propietario_telefono" for="propietario_telefono" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[0]//Teléfono?></label>
						        </div>
						        
						        <div class="input-field col s12 m4 l4">
						          <input disabled id="propietario_celular" name="propietario_celular" type="text" class="validate" length="20" maxlength="20" value="<?php echo $informacionPropietario['celular'] ?>">
						          <label id="label_propietario_celular" for="propietario_celular" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[2]//Celular?></label>
						        </div>
						        
						        <div class="input-field col s12 m4 l4">
		                            <input disabled id="pais" name="pais"  type="text" class="validate" onkeypress="buscarPaisreplica()" value="<?php echo $informacionPropietario['nombrePais'] ?>">
		                            <label id="label_propietario_pais" for="pais" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_general[5]//País (Escriba y seleccione)?></label> 
		                      </div>
						      	
						      </div><!-- Fin row-->
						      
						      <div class="row">
						      	<div class="input-field col s12 m12 l12">
						      		<input disabled id="propietario_email" name="propietario_email" type="email" class="validate" length="100" maxlength="100" value="<?php echo $informacionPropietario['email'] ?>">
						            <label id="label_propietario_email" for="propietario_email" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_general[4] //E-mail?></label>
						      	</div>
						      </div><!-- Fin row-->
						      
						      <div class="row">
						      	<div class="col s12 right-align" >
						      		<a class="waves-effect waves-light red btn" onclick="cerrarDatosPropietario()"><?php echo $lang_botones[3]//Cerrar?></a>
						      	</div>
						      </div>
						      
			
			              	
			              
			 	</div>
			 <!-- Fin Div para ver la información del propietario-->
			  
			  
			  
			  
			  <div class="row">
			  	
			  	<div class="col s12 m12 l12">
	      

					  <ul class="collection with-header">
					  	
					  	<li class="collection-header">
					  		
					  		<h4 id="tituloLi" class="center-align" ><?php echo $lang_index[49]//Tus mascotas o animales?>
					  			
					  			
					  			
					  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_index[50]//Nuevo?>" onclick="mostrarFormNuevoPaciente()">
					  				<i class="material-icons">add</i>
					  			</a>
					  			
					  			
					  		</h4>
					  		
					  		
					  		<!-- Formulario para editar un paciente-->
					  		<div id="divHidden_editarPaciente" style="display: none;">
					  			
											<br />
							  							<div class="row">
							  									
							  									<div class="col s12 m3 l3" >
							  										
							  										<div class="col s6 m6 l6">
							  											<img id="editarPacinete_fotoActual" src="../Public/img/logos/icon.png" alt="" class="responsive-img" style="max-height: 80px; max-width: 80px;"  >
							  										</div>
							  										
							  										<div class="col s6 m6 l6">
							  											<p>
																	      <input disabled class="with-gap" name="editarPacinete_paciente_estado" type="radio" id="radio5" value="vivo" checked />
																	      <label for="radio5"><?php echo $lang_nuevo[7]//Vivo?></label>
																	    </p>
																	    <p>
																	        <input disabled class="with-gap" name="editarPacinete_paciente_estado" type="radio" id="radio6" value="muerto" />
																	        <label for="radio6"><?php echo $lang_nuevo[8]//Murió?></label>
																	    </p>
							  										</div>
							  										
							  										
							  									</div>
							  											  				
												  				<!--<div class="file-field input-field col s12 m3 l3">
																      <div class="btn black">
																        <span><?php echo $lang_nuevo[9]//Cambiar foto?></span>
																        <input type="file" name="editarPacinete_fotoPaciente" id="editarPacinete_fotoPaciente">
																      </div>
																      <div class="file-path-wrapper">
																        <input id="editarPacinete_filePath" class="file-path validate" type="text" placeholder="png/jpg" >
																      </div>
												  				</div>-->
												  				
												  				<div class="input-field col s12 m l3">
												  					<input disabled id="editarPacinete_paciente_nombre" name="editarPacinete_paciente_nombre" type="text" class="validate" length="50" maxlength="50">
										          					<label id="editarPacinete_label_paciente_nombre" for="editarPacinete_paciente_nombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[10]//Nombre?></label>
												  				</div>
												  				
												  				<div class="input-field col s12 m3 l3">
												  					<input disabled id="editarPacinete_paciente_chip" name="editarPacinete_paciente_chip" type="text" class="validate" length="50" maxlength="50">
										          					<label id="editarPacinete_label_paciente_chip" for="editarPacinete_paciente_chip" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[11]//Código de chip?></label>
												  				</div>							  				
												  				
												  			</div><!-- Fin row-->
												  			
												  			<div class="row">
												  				
												  				<div class="col s12 m6 l6">
												  					
												  					<div class="col s12 m6 l6">
												  						<div class="input-field col s12 m12 l12">												  							
												  							<input disabled id="editarPacinete_paciente_especie" name="editarPacinete_paciente_especie" type="text" class="validate" onkeypress="editarBuscarEspecie()" >
										          							<label id="editarPacinete_label_paciente_especie" for="editarPacinete_paciente_especie" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[12]//Especie (escribe y selecciona)?></label>
												  						</div>
												  					</div>
												  					
												  					
												  					<div class="col s12 m6 l6">
												  						<div class="input-field col s12 m12 l12">
												  							<input disabled id="editarPacinete_paciente_raza" name="editarPacinete_paciente_raza" type="text" class="validate" onkeypress="editarBuscarRaza()"  >
										          							<label id="editarPacinete_label_paciente_raza" for="editarPacinete_paciente_raza" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[13]//Raza (escribe y selecciona) ?> </label>
												  						</div>
												  					</div>
												  					
												  					
												  				</div><!-- Fin col m4 l4-->
												  				
												  				
												  				
												  				
												  				<div class="col s12 m2 l2">
												  												  						
																		<p>
																	      <input disabled class="with-gap" name="editarPacinete_paciente_sexo" type="radio" id="radio7" value="M" />
																	      <label for="radio7"><?php echo $lang_nuevo[14]//Macho ?></label>
																	    </p>
																	    <p>
																	        <input disabled class="with-gap" name="editarPacinete_paciente_sexo" type="radio" id="radio8" value="H" />
																	        <label for="radio8"><?php echo $lang_nuevo[15]//Hembra ?></label>
																	    </p>									    
																	
																	
												  				</div>
												  				
												  				<div class="col s12 m4 l4">
												  					
												  					<div class="col s6 m4 l4">
												  						<div class="input-field col s12 m12 l12">
												  							<input disabled id="editarPacinete_fechaNacimiento" name="editarPacinete_fechaNacimiento" type="text" class="datetimepicker" maxlength="10" onblur="calcularTiempoDeVida(this.value,'resultadoFechas')">
										          					    	<label id="editarPacinete_label_fechaNacimiento" for="editarPacinete_fechaNacimiento" class="active" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[16]//Fecha de nacimiento?></label>
												  							<input type="hidden" id="hidden_errorFecha" name="hidden_errorFecha" value="0" />
												  						</div>
												  					</div>
												  					
												  					<div class="col s6 m8 l8">
												  						<span  id="editarPacinete_resultadoFechas" name="editarPacinete_resultadoFechas">&nbsp;</span>
												  					</div>
												  					
												  					
												  				</div>
												  				
					
												  			</div><!-- Fin row-->
												  			
												  			
												  			<div class="row">
												  				
												  				<div class="col s12 m2 l2">						  					
												  					
					
																		<p>
																	      <input disabled class="with-gap" name="editarPacinete_paciente_esterilizado" type="radio" id="radio9" value="Si" />
																	      <label for="radio9"><?php echo $lang_nuevo[17]//Esterilizado?></label>
																	    </p>
																	    <p>
																	        <input disabled class="with-gap" name="editarPacinete_paciente_esterilizado" type="radio" id="radio10" value="No" />
																	        <label for="radio10"><?php echo $lang_nuevo[18]//Sin esterilizar?></label>
																	    </p>											
																	
																	
												  				</div>
												  				
												  				<div class="input-field col s12 m2 l2">
												  					<input disabled id="editarPacinete_paciente_color" name="editarPacinete_paciente_color" type="text" class="validate" length="100" maxlength="100">
										          					<label id="editarPacinete_label_paciente_color" for="editarPacinete_paciente_color" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[19]//Color?></label>
												  				</div>
												  				
												  				
												  				<div class="col s12 m8 l8">
												  					
												  					<div class="col s12 m6 l6">
												  					
													  					<div class="input-field col s12 m12 l12">
													  						<input disabled id="editarPacinete_paciente_alimento" name="editarPacinete_paciente_alimento" type="text" class="validate" length="300" maxlength="300">
											          						<label id="editarPacinete_label_paciente_alimento" for="editarPacinete_paciente_alimento" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[20]//Alimento?></label>
													  					</div>
												  					
												  					</div>
												  					
												  					<div class="col s6 l3 m3">
												  					
													  					<div class="input-field  s12 m12 l12">
																		    <select disabled id="editarPacinete_frecuenciaAlimento" name="editarPacinete_frecuenciaAlimento" >
																		      <option value="1">1 <?php echo $lang_nuevo[22]//Vez (al día)?></option>
																		      <option value="2">2 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="3">3 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="4">4 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="5">5 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="6">6 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="7">7 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="8">8 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="9">9 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		      <option value="10">10 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
																		    </select>
																		    <label><?php echo $lang_nuevo[21]//Frecuencia alimento ?></label>
													  					</div>
												  					
												  					</div>
												  					
												  					<div class="col s6 l3 m3">
												  					
													  					<div class="input-field  s12 m12 l12">
																		    <input disabled id="editarPacinete_paciente_bano" name="editarPacinete_paciente_bano" type="text" class="validate" length="30" maxlength="30">
											          						<label id="editarPacinete_label_paciente_bano" for="editarPacinete_paciente_bano" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[24]//Frecuencia de baño?></label>
													  					</div>
												  					
												  					</div>
												  					
												  					
												  				</div><!-- Fin col 8-->						  				
					
												  				
												  			</div><!-- Fin row-->
					
										  			
										  			<div class="row">
										  				
										  				<div class="input-field col s12 m12 l12 right-align">
										  					<button class="waves-effect red darken-1 btn" onclick="cancelarEdicionPaciente()"><?php echo $lang_botones[3]//Cerrar?></button>
										      				
										      			</div>
										  				
										  			</div>

					  			
					  		</div>
					  		
					  		<!-- Fin Formulario para editar un paciente-->
					  		
					  		
					  	
					  		<div id="hideFormPaciente" style="display: none;">
					  			
					  			<form name="form_nuevoPaciente" id="form_nuevoPaciente" action="" method="post" enctype="multipart/form-data"> 
					  					
					  					<input type="hidden" name="idPropietarioPaciente" id="idPropietarioPaciente" value="<?php echo $informacionPropietario['idPropietario']?>" />
					  					
					  									  					
					  					<input type="hidden" name="envioFormNuevopaciente" id="envioFormNuevopaciente" value="envio" />
					  					
					  					<input type="hidden" name="idRaza" id="idRaza" value="" />
					  			
							  			<div class="row">
							  											  				
							  				<div class="input-field col s12 m4 l4">
							  					<input id="paciente_nombre" name="paciente_nombre" type="text" class="validate" length="50" maxlength="50">
					          					<label id="label_paciente_nombre" for="paciente_nombre" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[10]//Nombre?></label>
							  				</div>
							  				
							  				<div class="input-field col s12 m4 l4">
							  					<input id="paciente_chip" name="paciente_chip" type="text" class="validate" length="50" maxlength="50">
					          					<label id="label_paciente_chip" for="paciente_chip" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[11]//Código de chip?></label>
							  				</div>							  				
							  				
							  			</div><!-- Fin row-->
							  			
							  			<div class="row">
							  				
							  				<div class="col s12 m6 l6">
							  					
							  					<div class="col s12 m6 l6">
							  						<div class="input-field col s12 m12 l12">
							  							 <select name="idEspecie" id="idEspecie" onchange="habilitarRaza()" >
													      <option value="" disabled selected><?php echo $lang_index[51]//Elige una?></option>
													      <option value="1"><?php echo $lang_index[52]//Canina?></option>
													      <option value="2"><?php echo $lang_index[53]//Felina?></option>
													      <option value="3"><?php echo $lang_index[54]//Equina?></option>
													      <option value="4"><?php echo $lang_index[55]//Bovina?></option>
													      <option value="5"><?php echo $lang_index[56]//Roedor?></option>
													      <option value="6"><?php echo $lang_index[57]//Ave?></option>
													      <option value="7"><?php echo $lang_index[58]//Anfibia?></option>
													    </select>
													    <label><?php echo $lang_index[59]//Especie?></label>
							  						</div>
							  					</div>
							  					
							  					<div class="col s12 m6 l6">
							  						<div class="input-field col s12 m12 l12">
							  							<input id="paciente_raza" name="paciente_raza" type="text" class="validate" onkeypress="buscarRaza()" disabled  >
					          							<label id="label_paciente_raza" for="paciente_raza" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[13]//Raza (escribe y selecciona)?></label>
							  						</div>
							  					</div>
							  					
							  					
							  				</div><!-- Fin col m4 l4-->
							  				
							  				
							  				
							  				
							  				<div class="col s12 m2 l2">
							  												  						
													<p>
												      <input class="with-gap" name="paciente_sexo" type="radio" id="radio1" value="M" />
												      <label for="radio1"><?php echo $lang_nuevo[14]//Macho?></label>
												    </p>
												    <p>
												        <input class="with-gap" name="paciente_sexo" type="radio" id="radio2" value="H" />
												        <label for="radio2"><?php echo $lang_nuevo[15]//Hembra?></label>
												    </p>									    
												
												
							  				</div>
							  				
							  				<div class="col s12 m4 l4">
							  					
							  					<div class="col s6 m4 l4">
							  						<div class="input-field col s12 m12 l12">
							  							<input id="fechaNacimiento" name="fechaNacimiento" type="text" class="datetimepicker" maxlength="10" onblur="calcularTiempoDeVida(this.value,'resultadoFechas')">
					          					    	<label id="label_fechaNacimiento" for="fechaNacimiento" class="active" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[16]//Fecha de nacimiento?></label>
							  							<input type="hidden" id="hidden_errorFecha" name="hidden_errorFecha" value="0" />
							  						</div>
							  					</div>
							  					
							  					<div class="col s6 m8 l8">
							  						<span  id="resultadoFechas" name="resultadoFechas">&nbsp;</span>
							  					</div>
							  					
							  					
							  				</div>
							  				

							  			</div><!-- Fin row-->
							  			
							  			
							  			<div class="row">
							  				
							  				<div class="col s12 m2 l2">						  					
							  					

													<p>
												      <input class="with-gap" name="paciente_esterilizado" type="radio" id="radio3" value="Si" />
												      <label for="radio3"><?php echo $lang_nuevo[17]//Esterilizado?></label>
												    </p>
												    <p>
												        <input class="with-gap" name="paciente_esterilizado" type="radio" id="radio4" value="No" />
												        <label for="radio4"><?php echo $lang_nuevo[18]//Sin esterilizar?></label>
												    </p>											
												
												
							  				</div>
							  				
							  				<div class="input-field col s12 m2 l2">
							  					<input id="paciente_color" name="paciente_color" type="text" class="validate" length="100" maxlength="100">
					          					<label id="label_paciente_color" for="paciente_color" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[19]//Color?></label>
							  				</div>
							  				
							  				
							  				<div class="col s12 m8 l8">
							  					
							  					<div class="col s12 m6 l6">
							  					
								  					<div class="input-field col s12 m12 l12">
								  						<input id="paciente_alimento" name="paciente_alimento" type="text" class="validate" length="300" maxlength="300">
						          						<label id="label_paciente_alimento" for="paciente_alimento" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[20]//Alimento?></label>
								  					</div>
							  					
							  					</div>
							  					
							  					<div class="col s6 l3 m3">
							  					
								  					<div class="input-field  s12 m12 l12">
													    <select id="frecuenciaAlimento" name="frecuenciaAlimento" >
													      <option value="1">1 <?php echo $lang_nuevo[22]//Vez (al día)?></option>
													      <option value="2">2 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="3">3 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="4">4 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="5">5 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="6">6 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="7">7 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="8">8 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="9">9 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													      <option value="10">10 <?php echo $lang_nuevo[23]//Veces (al día)?></option>
													    </select>
													    <label><?php echo $lang_nuevo[21]//Frecuencia alimento?></label>
								  					</div>
							  					
							  					</div>
							  					
							  					<div class="col s6 l3 m3">
							  					
								  					<div class="input-field  s12 m12 l12">
													    <input id="paciente_bano" name="paciente_bano" type="text" class="validate" length="30" maxlength="30">
						          						<label id="label_paciente_bano" for="paciente_bano" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_nuevo[24]//Frecuencia de baño?></label>
								  					</div>
							  					
							  					</div>
							  					
							  					
							  				</div><!-- Fin col 8-->						  				

							  				
							  			</div><!-- Fin row-->

					  			
					  			</form>
					  			
					  			<div class="row">
					  				
					  				<div class="input-field col s12 m12 l12 right-align">
					  					<span id="mensajeErrorCheck" style="display: none;" ><?php echo $lang_nuevo[28]//Debes elegir si es un macho o una hembra y además indicar si se encuentra esterilizado o no?></span>
					  					<span id="mensajeErrorCheckMostrar" class="red-text text-darken-2" >&nbsp;</span>
					  					<button class="waves-effect red darken-1 btn" onclick="cancelarCreacionPaciente()"><?php echo $lang_botones[5]//Cancelar?></button>
					      				<button class="waves-effect waves-light btn" onclick="validarGuardarPaciente()"><?php echo $lang_botones[2]//Guardar?></button>
					      			</div>
					  				
					  			</div>
					  			
					  			
					  		</div><!-- Fin div hide para mostrar form nuevo paciente-->
					  		
					  		
					  	</li>

<?php

			//se recorre el listado de pacientes
			foreach ($listadoPacientes as $listadoPacientes1) {
				
						//texto para el sexo
						if($listadoPacientes1['sexo'] == 'M'){
							$sexo = "Macho";
						}else{
							$sexo = "Hembra";
						}//fin else
						
						//texto para esterilizado
						if ($listadoPacientes1['esterilizado'] == 'Si') {
							$esterilizado	= "Si";
						} else {
							$esterilizado	= "No";
						}//fin else
						
						
						
						$tiempoDeVida	= tiempoTranscurridoFechas($listadoPacientes1['fechaNacimiento']);
						
						$idPropietario			= $listadoPacientes1['idPropietario'];
						$idEspecie				= $listadoPacientes1['idEspecie'];
						$idRaza 				= $listadoPacientes1['idRaza'];
						$rutaFoto 				= $listadoPacientes1['urlFoto'];
						$estado 				= $listadoPacientes1['estado'];
						$idPaciente 			= $listadoPacientes1['idMascota'];
						$nombre 				= $listadoPacientes1['nombre'];
						$chip 					= $listadoPacientes1['numeroChip'];
						$especie 				= $listadoPacientes1['EspecieNombre'];
						$raza 					= $listadoPacientes1['RazaNombre'];
						$sexo 					= $listadoPacientes1['sexo'];
						$fechaNacimiento 		= $listadoPacientes1['fechaNacimiento'];
						$esterilizado 			= $listadoPacientes1['esterilizado'];
						$color 					= $listadoPacientes1['color'];
						$alimento 				= $listadoPacientes1['alimento'];
						$frecuenciaAlimento		= $listadoPacientes1['frecuenciaDiaria']; 
						$bano					= $listadoPacientes1['frecuenciaBanoDias'];
						
						//if($rutaFoto == ""){
							$rutaFoto =	"http://www.nanuvet.com/Public/img/logos/icon.png";
						//}else{
							//$rutaFoto =	"http://www.nanuvet.com/Public/uploads/".$_SESSION['BDC_carpeta']."/img_pacientes/".$rutaFoto;
						//}

						
						$parametrosEditar = " '".$idPropietario."', '".$idEspecie."', '".$idRaza."', '".$rutaFoto."', '".$estado."', '".$idPaciente."', '".$nombre."', '".$chip."', '".$especie."', '".$raza."', '".$sexo."', '".$fechaNacimiento."', '".$esterilizado."', '".$color."', '".$alimento."' ,'".$frecuenciaAlimento."', '".$bano."'   ";
			
?>
			  	
					    <li class="collection-item avatar <?php if($estado != 'vivo' ){?>grey lighten-1<?php } ?> ">
					    	
					     				    	
					      
					      <span class="title"><?php echo $listadoPacientes1['nombre']?></span>
					      
					      <div class="row hoverable tooltipped" style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_nuevo[29]//Ver la información de ?><?php echo $listadoPacientes1['nombre']?>" onclick="editarpaciente(<?php echo $parametrosEditar ?>)" >
					      	
					      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_nuevo[30]//Raza:?></strong></div>
					      	<div class="col s6 m2 l2"><?php echo $listadoPacientes1['RazaNombre'] ?></div>					      	
					      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_nuevo[31]//Sexo:?></strong></div>
					      	<div class="col s6 m2 l1"><?php echo $sexo?></div>
					      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_nuevo[32]//Edad:?></strong></div>
					      	<div class="col s6 m2 l2"><?php echo $tiempoDeVida ?> </div>
					      	<div class="col s6 m1 l1" style="text-align: right;" ><strong><?php echo $lang_nuevo[33]//Esterilizado(a):?></strong></div>
					      	<div class="col s6 m2 l2"><?php echo $esterilizado?></div>
					      	
					      </div><!-- Fin row-->
					      
					      <a href="<?php echo Config::ruta()?>replica/<?php echo $informacionPropietario['idPropietario']?>/<?php echo $idPaciente?>/historiaClinica/consultas/" class="secondary-content">
					      	<i class="fa fa-info-circle fa-3x tooltipped" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_nuevo[34]//Ver la historia clinica de?> <?php echo $listadoPacientes1['nombre']?>" aria-hidden="true"></i>
					      </a>
					      
					    </li>
					    

<?php				
			}//fin foreach

?>					    
					    
					    
					    
					   </ul>
					  
					  
				      
				      
			  	</div><!-- Fin col-->
			  	
			  </div><!-- Fin row-->
			  
                          
              
              
              
             </div>
           </div>	
		</div>		
	</div>
	
</main>