<main>
	<div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
              
              <span class="card-title">
              <div class="row">
              		<div class="col s6">
              			 <div data-activates="slide-out" class="chip button-collapse" style="cursor: pointer;">
		              		<i class="fa fa-bars" aria-hidden="true"></i>
						    <?php echo $lang_reportes[12]//Reportes?>				    
						  </div>
						  <?php echo $lang_reportes[0] //Gerencial?>
						  
              		</div>
              		<div class="col s6 right-align">
              			
              			<i style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_personalizados[44]//Ver tutorial ?>" class="fa fa-play tooltipped" aria-hidden="true" onclick="playVideoTutorial()"></i>

              		</div>
              	</div>
              </span>
              
              
              <div class="row">	
					<div id="div_videoTutorial" style="display: none;" class="col s12 center-align">
							<h5>Video-tutorial</h5>
						 <video id="videoTutorial_personalizados" class="responsive-video" controls>
						    <source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/reportes/reportes.mp4" type="video/mp4">
						  </video>
						  <h6 class="center-align">
						  	<a class="waves-effect red darken-1 btn" onclick="cerrarVideoTutorial()"><i class="fa fa-stop" aria-hidden="left"></i> <?php echo $lang_personalizados[28] //Cerrar video?></a>
						  </h6>
					</div><!-- Fin div col video-->
				</div> 
				
				<div class="row">
					
						
						<div class="input-field col s4">
				          <i class="fa fa-calendar prefix" aria-hidden="true"></i>
				          <input  id="fechaInicial" name="fechaInicial" type="text" class="validate fechaInicio">
				          <label class="label_fechaInicial" for="fechaInicial" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_reportes[13]//Fecha inicial?></label>
				        </div>
				        
				        <div class="input-field col s4">
				          <i class="fa fa-calendar prefix" aria-hidden="true"></i>
				          <input id="fechaFinal" name="fechaFinal" type="text" class="validate fechaFin">
				          <label class="label_fechaFinal" for="fechaFinal" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_reportes[14]//Fecha final?></label>
				        </div>
						
			        
			        <div class="input-field col s4 center-align">
			        	<a class="waves-effect waves-light btn" onclick="gerencial_filtrarFechas()"><?php echo $lang_reportes[21]//Buscar?></a>
			        	<a class="waves-effect waves-light black btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_reportes[22]//Exportar a hoja de calculo?>" onclick="exportarHCalculo()"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
			        	<a class="waves-effect waves-light black btn tooltipped" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_reportes[83]//Exportar a pdf?>" onclick="exportarPdf()" ><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
			        </div>
					
				</div><!-- Fin row-->
				
				<form id="form_excel" name="form_excel" action="http://www.nanuvet.com/Controllers/impresiones/hojaCalculo/hojaCalculoController.php" method="post" target="_blank">
					<input type="hidden" id="envioForm" name="envioForm" value="" />
				</form>
				
				<form id="form_pedf" name="form_pedf" action="http://www.nanuvet.com/Controllers/impresiones/pdfGeneral/pdfGeneralController.php" method="post" target="_blank">
					<input type="hidden" id="envioFormPdf" name="envioFormPdf" value="" />
				</form>
				
				<div id="resultadoReporte">
					
					<?php
					
						require_once("resultadoReporteGerencial.phtml");
					
					?>
					
					
				</div><!--Fin Div resultado reportes-->

			 </div>
          </div>
        </div>
      </div>
</main>