<main >
	
	 <div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
	  
              <span class="card-title">
              	<div class="row">
              		<div class="col s6">
              			 <div data-activates="slide-out" class="chip button-collapse" style="cursor: pointer;">
		              		<i class="fa fa-bars" aria-hidden="true"></i>
						    <?php echo $lang_listados[1]//Listas?>				    
						  </div>
              		</div>
              		<div class="col s6 right-align">
              			
              			<i style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_personalizados[44]//Ver tutorial ?>" class="fa fa-play tooltipped" aria-hidden="true" onclick="playVideoTutorial()"></i>

              		</div>
              	</div>
              </span>
              
              
					<div class="row">	
						<div id="div_videoTutorial" style="display: none;" class="col s12 center-align">
								<h5><?php echo $lang_personalizados[27] //Tutorial personalizados?></h5>
							 <video id="videoTutorial_personalizados" class="responsive-video" height="600" width="600"  controls>
							 	
							 	<?php 
							 		
							 		if(is_file("Public/videos/tutoriales/".$idiomaIndex."/listados/listados.mp4")){
							 	
								?>
										<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/listados/listados.mp4" type="video/mp4">
								<?php	
							 		}else{
							 	?>
							 			<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/FueraServicio/fueraServicio.mp4" type="video/mp4">
							 	<?php	
							 		}
							 	?>
							 	
							    
							  </video>
							  <h6 class="center-align">
							  	<a class="waves-effect red darken-1 btn" onclick="cerrarVideoTutorial()"><i class="fa fa-stop" aria-hidden="left"></i> <?php echo $lang_personalizados[28] //Cerrar vídeo?></a>
							  </h6>
						</div><!-- Fin div col video-->
					</div>
				
				<div class="row">
					
					<div class="col s12 m12 l12">
						
						<ul class="collection with-header">
							
							<li class="collection-header">
								<h4 id="tituloLi" class="center-align" ><?php echo $lang_servicios[0]//Servicios?>
						  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_servicios[1]//Nuevo servicio?>" onclick="mostrarFormNuevoServicio()">
						  				<i class="material-icons">add</i>
						  			</a>
						  		</h4>						  		
						  		<br />
						  		
						  		<div id="hidden_editarServicio" style="display: none;">						  			
						  			
						  			<div class="row">
				                      	<div class="col s12 m12 l12">
				                      		<h4 class="center-align"><?php echo $lang_servicios[2]//Editar servicio?></h4>
				                      	</div>
				                      </div>
						  			<div class="row">
						  				<form id="form_editarServicio" name="form_editarServicio" action="" method="post" >
						  					<input type="hidden" id="idEditarServicio" name="idEditarServicio" value="" />
						  					<input type="hidden" id="replicaNombre" name="replicaNombre" value="" />
							  				<div class="row">
                          
						                      
						                      <div class="input-field col s12 m6 l6">						                            
						                            <input id="nombreEditarServicio" name="nombreEditarServicio" type="text" class="validate" length="100" maxlength="100">
						                            <label id="label_nombreEditarServicio" for="nombreEditarServicio"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_servicios[3]//Nombre servicio?></label> 
						                      </div> 
						                      
						                      <div class="input-field col s12 m4 l4">						                            
						                            <input id="codigoEditarServicio" name="codigoEditarServicio" type="text" class="validate" length="10" maxlength="10">
						                            <label id="label_codigoEditarServicio" for="codigoEditarServicio"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_servicios[4]//Código servicio?></label> 
						                      </div> 
						                      
						                      <div class="input-field col s12 m2 l2">						                            
						                            <i id="editarbtnGenerarCodigo" class="fa fa-random fa-2x tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_servicios[5]//Generar código aleatorio?>" aria-hidden="true" style="cursor: pointer;" onclick="generarCodigoServicio('codigoEditarServicio')"></i> 
						                      </div> 
						                      
						                    </div>
						                      
						                   <div class="row">
						                      
						                      <div class="input-field col s12 m6 l6">						                            
						                           <input id="descripcionEditarServicio" name="descripcionEditarServicio" type="text" class="validate" length="200" maxlength="200">
						                           <label id="label_descripcionEditarServicio" for="descripcionEditarServicio" style="width:95%; text-align: left;" ><?php echo $lang_servicios[6]//Descripción?></label>
						                      </div> 
						                      
						                      <div class="input-field col s12 m4 l4">		
						                      	   <i class="fa fa-usd prefix" aria-hidden="true"></i>				                            
						                           <input id="precioEditarServicio" name="precioEditarServicio" type="text" class="validate" length="10" maxlength="10" onkeypress="return soloNumerosPuntos(event)" >																		<!-- Precio -->
						                           <label id="label_precioEditarServicio" for="precioEditarServicio" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_diagnosticos[7]." ".$lang_general[13]//(Utilizar punto solo para decimales)?></label>
						                      </div> 
						                      
						                  </div><!-- fin row-->
							  				
						  				</form>
						  				<div class="input-field col s12 m12 l12 right-align">					  					
						  						<a class="waves-effect red darken-1 btn" onclick="cancelarEdicionServicio()" ><?php echo $lang_botones[5]//Cancelar?></a>		
						  						<a class="waves-effect waves-light btn" onclick="comprobarEdicionServicio()" ><?php echo $lang_botones[4]//Editar?></a>				  									  					
						  				</div>
						  			</div>
						  			
						  		</div>
						  		
						  		<div id="hidden_NuevoServicio" style="display: none ;">
						  			
						  			<div class="row">
						  				<form class="col s12 m12 l12" id="form_nuevoServicio" name="form_nuevoServicio" action="" method="post">
						  					
						                    <input type="hidden" id="envioNuevoServicio" name="envioNuevoServicio"  value="envio"/>
						                    
						                    <div class="row">
                          
						                      
						                      <div class="input-field col s12 m6 l6">						                            
						                            <input id="nombreServicio" name="nombreServicio" type="text" class="validate" length="100" maxlength="100">
						                            <label id="label_nombreServicio" for="nombreServicio"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_servicios[7]//Nombre del nuevo servicio?></label> 
						                      </div> 
						                      
						                      <div class="input-field col s12 m4 l4">						                            
						                            <input id="codigoServicio" name="codigoServicio" type="text" class="validate" length="10" maxlength="10">
						                            <label id="label_codigoServicio" for="codigoServicio"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_servicios[8]//Código del nuevo servicio?></label> 
						                      </div> 
						                      
						                      <div class="input-field col s12 m2 l2">						                            
						                            <i id="btnGenerarCodigo" class="fa fa-random fa-2x tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_diagnosticos[10]//Generar código aleatorio ?>" aria-hidden="true" style="cursor: pointer;" onclick="generarCodigoServicio('codigoServicio')"></i> 
						                      </div> 
						                      
						                    </div>
						                      
						                   <div class="row">
						                      
						                      <div class="input-field col s12 m6 l6">						                            
						                           <input id="descripcionServicio" name="descripcionServicio" type="text" class="validate" length="200" maxlength="200">
						                           <label id="label_descripcionServicio" for="descripcionServicio" style="width:95%; text-align: left;" ><?php echo $lang_servicios[6]//Descripción?></label>
						                      </div> 
						                      
						                      <div class="input-field col s12 m4 l4">		
						                      	   <i class="fa fa-usd prefix" aria-hidden="true"></i>				                            
						                           <input id="precioServicio" name="precioServicio" type="text" class="validate" length="10" maxlength="10" onkeypress="return soloNumerosPuntos(event)" >																	<!-- Precio-->
						                           <label id="label_precioServicio" for="precioServicio" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_diagnosticos[7]." ".$lang_general[13]//(Utilizar punto solo para decimales)?></label>
						                      </div> 
						                      
						                  </div><!-- fin row-->
						                  
						                  <div class="input-field col s12 m12 l12 right-align">
						                  	<a class="waves-effect red darken-1 btn" onclick="cancelarGuardadoNuevoServicio()"><?php echo $lang_botones[5]//Cancelar?></a>
						                    <a class="waves-effect waves-light btn" onclick="validarGuardadoNuevoServicio()"><?php echo $lang_botones[2]//Guardar?></a>
						                  </div><!-- fin row-->
						  					
						  					
						  				</form>
						  			</div><!-- Fin row-->
						  		</div><!-- fin Div oculto para formulario del nuevo servicio-->
						  		
						  		
							</li>
							
						</ul>
						
					</div>				
					
				</div><!-- Fin row-->
				
				
				<div class="row">
					<div class="input-field col s10 m3 l3">
						<i class="fa fa-search prefix" aria-hidden="true"></i>
						<input placeholder="<?php echo $lang_servicios[13]//Buscar servicio (Escribe y selecciona)?>" id="buscarServicio" type="text" class="validate" onkeypress="buscarServicioListados()" >
						<input type="hidden" id="idServicioBuscado" value="" />
					</div>
					<div class="input-field col s2 m2 l2">
						<i id="btnCancelarBusqueda" class="fa fa-times-circle fa-3x" aria-hidden="true" style="cursor: pointer; display: none;" onclick="cerrarBusquedaServicio()"></i>
					</div>
				</div>
				
				
				<div class="row">
					
					<div class="col s12 m12 l12">
						<span id="spanActivar" style="display: none;"><?php echo $lang_servicios[9]//Activar servicio?></span>
						<span id="spanDesactivar" style="display: none;"><?php echo $lang_servicios[10]//Desactivar servicio?></span>
						
							<div id="resultadoServiciosAjax">
								
							</div><!-- Fin para el resultado de los servicios ajax-->
							
							<div id="resultadoServicios">
								<table class="bordered highlight centered responsive-table">
									
									<thead>
										<tr>
											<th><?php echo $lang_servicios[11]//Servicio?></th>
											<th><?php echo $lang_servicios[12]//Código?></th>
											<th><?php echo $lang_servicios[6]//Descripción?></th>
											<th><?php echo $lang_diagnosticos[7]//Precio?></th>
											<th><?php echo $lang_general[12]//Estado?></th>
										</tr>
									</thead>
									
									<tbody>
										
										<?php									
											foreach ($listadoServicios as $listadoServicios1) {
												
												if($listadoServicios1['estado'] == 'A'){																																																			//Desactivar servicio
													$btn = '<span id="spanB_'.$listadoServicios1['idServicio'].'"> <a id="'.$listadoServicios1['idServicio'].'" class="waves-effect waves-light btn tooltipped" onclick="desactivarServicio(this.id)"  data-position="right" data-delay="50" data-tooltip="'.$lang_servicios[10].'" ><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}else{																																																											//Activar servicio
													$btn = '<span id="spanB_'.$listadoServicios1['idServicio'].'"> <a id="'.$listadoServicios1['idServicio'].'" class="waves-effect red darken-1 btn tooltipped" onclick="activarServicio(this.id)" data-position="right" data-delay="50" data-tooltip="'.$lang_servicios[9].'"><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}
												
												$parametros = "'".$listadoServicios1['idServicio']."','".$listadoServicios1['nombre']."','".$listadoServicios1['codigo']."','".$listadoServicios1['descripcion']."','".$listadoServicios1['precio']."'";
										?>
										
											<tr style="cursor: pointer;">
												<td onclick="editarServicio(<?php echo $parametros?>)" ><?php echo $listadoServicios1['nombre']?></td>
												<td onclick="editarServicio(<?php echo $parametros?>)"><?php echo $listadoServicios1['codigo']?></td>
												<td onclick="editarServicio(<?php echo $parametros?>)"><?php echo $listadoServicios1['descripcion']?></td>
												<td onclick="editarServicio(<?php echo $parametros?>)"><?php echo $listadoServicios1['precio']?></td>
												<td>
													<?php echo $btn ?>											
												</td>
											</tr>											
												
										<?php		
											}//fin foreach								
										?>
										
										
										
									</tbody>
									
									
								</table>
								
							</div><!-- Fin div para los resultados de los servicios-->	
						
					</div>
					
				</div><!-- Fin row-->
				
				

			 </div>
          </div>
        </div>
      </div>


	<!-- paginacion -->
		<footer class="page-footer white">
					<?php
					
					// render the pagination links
					$pagination->render();
					
					?>
		</footer>	
	<!-- fin paginacion -->	
	
</main>