<main>
	 <div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
              <span class="card-title"><?php echo $lang_menu[4] //reportes?></span>
				
				<div class="row">
					<br />
					<br />
					<div class="col s12 center-align">
						<a href="<?php echo Config::ruta()?>reportes/gerencial/" class="waves-effect waves-light btn-large"><?php echo $lang_reportes[0]//Gerencial?></a>
					</div>
					<br />
					<br />
					
					<br />
					 <div class="collection">
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/citas/"><?php echo $lang_reportes[1]//Citas?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/cirugias/"><?php echo $lang_reportes[2]//Cirugías?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/consultas/"><?php echo $lang_reportes[3]//Consultas?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/desparasitantes/"><?php echo $lang_reportes[4]//Desparasitantes?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/examenes/"><?php echo $lang_reportes[5]//Exámenes?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/formulas/"><?php echo $lang_reportes[6]//Formulas?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/hospitalizaciones/"><?php echo $lang_reportes[7]//Hospitalizaciones?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/inventario/"><?php echo $lang_reportes[8]//Inventario?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/pacientes/"><?php echo $lang_reportes[9]//Pacientes?></a>
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/propietarios/"><?php echo $lang_reportes[10]//Propietarios?></a>				           
				            <a class="collection-item" href="<?php echo Config::ruta()?>reportes/vacunas/"><?php echo $lang_reportes[11]//Vacunas?></a>
				      </div>
					
				</div><!-- Fin row-->

			 </div>
          </div>
        </div>
      </div>
</main>