
                <div class="right-align">
                    <img class="responsive-img" src="<?php echo Config::ruta()?>Public/img/logos/NanuVet.png">
                </div>

<div class="container center-align">
    
    <video autoplay loop muted id="myVideo">
	 	<source src="Public/videos/pugComputer.mp4" type="video/mp4"/>
	</video>
    
    
				<div class="container" style="margin-top: 12%;" >
                      <div class="row">
                        <div class="col s12 m12 l12">
                          <div class="card blue-grey darken-1">
                            <div class="card-content white-text">
                              <span class="card-title"><?php echo $lang_construccion[0] ?></span>
                              <p><?php echo $lang_construccion[1] ?></p>
                              <span class="card-title"><?php echo $lang_construccion[2] ?></span>
                              <div id="countdown"></div>
                            </div>
                          </div>
                        </div>
                      </div>
	               
	           </div><!-- Fin container-->
	           

    
</div>

