<!-- Modal para decidir la forma de impresion -->

<div id="modal_impresionHC" class="modal" style="margin-top: 5%;">
    <div class="modal-content">
      <h4 class="center-align"><?php echo $lang_historiaClinica[10]//Imprimir historia clínica?></h4>
      <br />
      <div class="row">
      	<div class="col s12 center-align">      		
			<a target="_blank"  class="waves-effect waves-light btn modal-close" href="http://www.nanuvet.com/impresiones/HCFechas/<?php echo $_GET['id1']  ?>/" ><?php echo $lang_historiaClinica[11]//Por fechas?></a>
			<a target="_blank"  class="waves-effect waves-light btn modal-close" href="http://www.nanuvet.com/impresiones/HCElementos/<?php echo $_GET['id1']  ?>/" ><?php echo $lang_historiaClinica[12]//Agrupando elementos?></a>
      	</div>
      </div>
      
      
    </div>
    <div class="modal-footer">
      <a href="javascript:void(0)" class=" modal-action modal-close waves-effect waves-red btn-flat"><?php echo $lang_botones[5]//Cancelar?></a>
    </div>
  </div>


<!-- Fin  Modal para decidir la forma de impresion -->

<!-- Modal para texto observaciones -->

<div id="modal_observacionesVacuna" class="modal" style="height: 78% !important ; margin-top: 3%; width: 75% !important ; max-height: 100% !important ; overflow-y: hidden !important ;">
    <div class="modal-content" style="height: 85%;">
       <iframe id="iframe_observaciones" src="http://www.nanuvet.com/Views/Layout/editorDeTexto.phtml" style="border:none; height: 100%; width: 100%;"></iframe>
    </div>
    <div class="modal-footer">
    	<div class="input-field">    		
	      <a class=" modal-action modal-close waves-effect waves-light btn" onclick="vacuna_ObtenerTxtObservacionesVacuna()" ><?php echo $lang_general[14]//Aplicar?></a>
	      <a class=" modal-action modal-close waves-effect red darken-1 btn" style="margin-right: 10px;"><?php echo $lang_general[15]//Descartar?></a>
        </div>
    </div>
  </div>


<!--Fin  Modal para el observaciones -->




<main>
		
	 <div class="row">
 	
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
            	
					<div class="row">
						<div class="col s12 l12 m12">
					 			
					 		<a href="http://www.nanuvet.com/nuevo/<?php echo $datosPP_idPropietario?>">
							  <div class="chip" style="cursor: pointer;" >
							    <?php echo $lang_consultas[9]//Propietario:?> <?php echo "(".$datosPP_identificacionPropietario.") ".$datosPP_nombrePropietario." ".$datosPP_apellidoPropietario." -- ".$datosPP_celularPropietario?>
							  </div>
							</a>	
							  
							  <div class="chip">
							  	
							  	<?php
							  		if($datosPP_urlFotoPaciente != ""){
							  	?>
							  			<img  src="<?php echo "../../../Public/uploads/".$_SESSION['BDC_carpeta']."/img_pacientes/".$datosPP_urlFotoPaciente ?>" alt="foto">
							  	<?php
							  		}
									
									if($datosPP_sexoPaciente == 'M'){
										$sexoP	= $lang_consultas[10]/*Macho*/;
									}else{
										$sexoP	= $lang_consultas[11]/*Hembra*/;
									}
									
									if($datosPP_esterilizadoPaciente == "Si"){
										$esterilizadoP = $lang_consultas[12]/*Si*/;
									}else{
										$esterilizadoP = $lang_consultas[13]/*No*/;
									}
									
							  	?>							  								  
							    					<!-- -Nombre: -->												<!-- -Sexo:-->								<!-- -Edad:-->															<!-- -Esterilizado:-->								<!-- -Raza: -->
							    <?php echo "<u>/".$lang_consultas[14]."</u> ".$datosPP_nombrePaciente."   <u>/".$lang_consultas[15]."</u> ".$sexoP."   <u>/".$lang_consultas[16]."</u> ".$datosPP_edadPacientePaciente."   <u>/".$lang_consultas[17]."</u> ".$esterilizadoP."   <u>/".$lang_consultas[18]."</u> ".$datosPP_nombreRazaPaciente ?>
							  
							  	<?php							  
								  	if(sizeof($comprobarHospitalizacionActiva) > 0){
								  ?>
								  	
								  		<div class="chip orange">
								  			<?php echo $lang_historiaClinica[13]//Paciente Hospitalizado?>
								  		</div>
								  	
								  <?php
								  	}
								  ?>
							  
							  </div>
							  
							  <a class="btn-floating waves-effect waves-light black tooltipped" data-position="bottom" data-delay="50" data-tooltip="Imprimir historia clínica" onclick="tipoImpresionHistoriaClinica()" ><i class="fa fa-print" aria-hidden="true"></i></a>
        
					 	</div>
					</div>

					<div class="row">
						
						<div class="col s12 m12 l12 ">
													
						<ul class="tabs" style="overflow-x: auto !important;">
					        <li class="tab col s1 m1 l1"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/cirugias/')" class="black-text" ><?php echo $lang_historiaClinica[0]//Cirugías?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalCirugias?></span></a></li>
					        <li class="tab col s1 m1 l1"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/consultas/')" class="black-text" ><?php echo $lang_historiaClinica[1]//Consultas?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalConsultas?></span></a></li>
					        <li class="tab col s1 m1 l1"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/desparasitantes/')" class="black-text" ><?php echo $lang_historiaClinica[2]//Desparasitantes?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuDesparasitantes?></span></a></li>
					        <li class="tab col s1 m1 l1"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/examenes/')" class="black-text" ><?php echo $lang_historiaClinica[3]//Exámenes?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalExamenes?></span></a></li>
					        <li class="tab col s1 m1 l1"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/formulas/')" class="black-text" ><?php echo $lang_historiaClinica[4]//Formulas?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalFormulas?></span></a></li>
					        <li class="tab col s2 m2 l2"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/hospitalizacion/')" class="black-text" ><?php echo $lang_historiaClinica[5]//Hospitalizaciones?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalHospitalizaciones?></span></a></li>
					        <li class="tab col s1 m1 l1 grey lighten-2"><a href="javascript:void(0)" onclick="redireccionEnHC('http://www.nanuvet.com/historiaClinica/<?php echo $_GET['id1']?>/vacunas/')" class="black-text active" ><?php echo $lang_historiaClinica[6]//Vacunas?><span class="Bootstrapbadge teal lighten-2"><?php echo $menuTotalVacunas?></span></a></li>
					        
						</ul>
							
						</div>
						
					</div><!-- Fin row-->


				<div class="row">
					
					<div class="col s12 m12 l12">
						
						<ul class="collection with-header">
							
							<li class="collection-header">
								
								<h4 id="tituloLi" class="center-align"><?php echo $lang_vacunas[11]//Aplicaciones de vacunas?>
									<?php
										//saber si tiene permiso para crear vacunacion
											if(in_array("79", $_SESSION['permisos_usuario'] )){
										?>
						  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_vacunas[12]//Nueva aplicación?>" onclick="abrirFormNuevaVacuna()">
						  				<i class="material-icons">add</i>
						  			</a>
						  			<?php
						  				}//fin permiso crear vacunacion
						  			?>
						  		</h4>						  		
						  		<br />
								<?php
									//saber si tiene permiso para crear vacunacion
										if(in_array("79", $_SESSION['permisos_usuario'] )){
									?>
								<div id="hidden_nuevaVacuna" style="display: none;" >
									
									<div class="col s12 m12 l12">
			                      		<h4 class="center-align"><?php echo $lang_vacunas[13]//Nueva aplicación de Vacuna?></h4>
			                      	</div>
									
									<form id="form_nuevaVacuna" name="form_nuevaVacuna" method="post" action="" >
										
										<input type="hidden" class="modificarIndicatorVacuna" id="hidden_evioFormNuevaVacuna" name="hidden_evioFormNuevaVacuna" value="enviar" />
										<input type="hidden" id="idPaciente" name="idPaciente" value="<?php echo $_GET['id1'] ?>" />
										<input type="hidden" id="idVacunaBuscada" name="idVacunaBuscada" value="0" />
										<input type="hidden" id="resultadoIdProducto" name="resultadoIdProducto" value="0" />
										<input type="hidden" id="cantidadDisponible" name="cantidadDisponible" value="0" />
									
										<input type="hidden" id="idPacienteReplica" name="idPacienteReplica" value="<?php echo $datosPP_idReplica?>" />
									
										 <div class="row">
										 	
										 		<div class="col s12 m4 l4 input-field">								    			
									    				<span id="errorSinCantidad" style="display: none;"><?php echo $lang_vacunas[14]//Sin cantidad disponible en el inventario?></span>
									    				<span id="errorNoVinculado" style="display: none;"><?php echo $lang_vacunas[15]//No vinculado con el inventario (Igual puedes guardar la aplicación)?></span>
									    				<span id="errorIncompleto" style="display: none;"><?php echo $lang_error[0]//Debe completar este campo?></span>
									    				<input id="buscarVacuna" type="text" class="validate" onkeypress="vacuna_buscarVacuna()" onblur="validarClaseDelabelVacuna()">
												    	<label id="label_buscarVacuna" for="buscarVacuna" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;"><?php echo $lang_vacunas[7]//Buscar vacuna (Escribe y slecciona)?></label>
									    				
									    		</div><!-- Fin col -->
										 	
										 		
										 		<div class="col s12 m4 l4 input-field">
										 			<input id="fechaProximaVacuna" name="fechaProximaVacuna" type="text" class="datetimepicker" maxlength="10" >
					          					    <label id="label_fechaProximaVacuna" for="fechaProximaVacuna" class="active" data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:100%; text-align: left;" ><?php echo $lang_vacunas[16]//Fecha próxima vacuna?></label>
										 		</div>
										 	
										 </div><!-- Fin row-->
										 
										 <div class="row">							 	
										 		
									    		<div class="input-field col s12 m12 l12">
									    			
									    			<span class="prefix">
									    					<i class="fa fa-pencil-square-o modal-trigger" aria-hidden="true" href="#modal_observacionesVacuna" style="cursor: pointer;" ></i>									    					
									    					<i class="fa fa-trash" aria-hidden="true" style="cursor: pointer;" onclick="vacuna_limpiarTextareaObservacionesVacuna()"></i>
									    				</span>
									    				
									    				<div id="tituloObservaciones" style="display: none;">
									    					<div>
									    						<span style="text-align: center;"><h5><?php echo $lang_vacunas[17]//Observaciones?> <i  style="cursor: pointer; margin-left: 20%;" class="fa fa-eraser" aria-hidden="true" onclick="vacuna_recuperarTextareaObservaciones()"></i> </h5> </span>
									    					</div>
									    					
									    				</div>
									    				
									    				<span id="contenidoTextoTexarea_observaciones" style="display: none;"></span>
									    				
									    				
									    				<div id="contenidoEditorObservaciones" style="display: none; overflow-y: scroll; max-height: 120px; min-height: 120px; margin-left: 6%;">
									    					
									    				</div>		
									    									    					
												        <textarea id="observaciones" name="observaciones" class="materialize-textarea" style="max-height: 12rem; min-height: 12rem !important; overflow-y: scroll;"></textarea>
												        <label id="label_observaciones" for="observaciones"><?php echo $lang_vacunas[17]//Observaciones?></label>
												        
									    		</div>
									    		
									    </div><!-- Fin row-->
									    	
									    							    				
						    			</form>									    
									    	
								    	<div class="row">
								    		<div class="col s12 m12 l12 right-align">
								    			
								    			<!-- textos para mostrar alerta cancelar vacuna-->
									       			<span id="estaSeguro" style="display: none;"><?php echo $lang_vacunas[18]//Esta seguro de cancelar la aplicación de vacuna??></span>
									       			<span id="Seperderan" style="display: none;"><?php echo $lang_consultas[53]//Se perderán todos los datos?></span>
									       			<span id="SiCancelarla" style="display: none;"><?php echo $lang_consultas[54]//Si, cancelarla?></span>
								    												    			
								              	<a class="waves-effect red darken-1 btn" onclick="cancelarGuardadoNuevaAplicacionVacuna()"><?php echo $lang_botones[5]//Cancelar?></a>					  								
	                    						<a class="waves-effect waves-light btn" onclick="validarGuardadoNuevaAplicacionVacuna()"><?php echo $lang_botones[2]//Guardar?></a>									    			
								    		</div>
								    	</div>
									    		    	
									
								</div><!-- Fin div para nueva vacuna-->
								<?php
						  				}//fin permiso crear vacunacion
						  			?>
						  	</li>
						  	
						</ul>
					</div><!-- Fin col-->
				</div><!-- Fin row-->






				<div class="row">
					
					<div class="col s12 m12 l12">
					
						  <ul class="collapsible popout" data-collapsible="accordion">
						  	
						  	<?php
								foreach ($listadoVacunasPaciente as $listadoVacunasPaciente1) {
									
							?>		
								
									<li>							
								      	<div class="collapsible-header">
								      		<i class="fa fa-file-text" aria-hidden="true"></i><?php echo $listadoVacunasPaciente1['fecha']." / ".$listadoVacunasPaciente1['nombreSucursal'] ?>


									
										</div>
										
									  	<div class="collapsible-body">
						      				<br />
						      				<div class="row">
						      					<div class="col s12 m2 l2 center-align valign">
								      				<a href="http://www.nanuvet.com/impresiones/vacunas/<?php echo $listadoVacunasPaciente1['idMascotaVacunas']  ?>/" target="_blank" class="waves-effect waves-light btn"><i class="fa fa-print left" aria-hidden="true"></i><?php echo $lang_botones[9]//Imprimir?></a>
								      			</div>
						      				</div>
								      		
								      		
								      		<div class="row">
								      			<div class="col s12 m3 l3">
								      				<h6><b><?php echo $lang_vacunas[3]//Nombre vacuna?>:</b></h6>
								      				<p>
		 												<?php echo $listadoVacunasPaciente1['nombre'] ?> 
										      		</p>
								      			</div>
								      			<div class="col s12 m3 l3">
								      				<h6><b>Descripción:</b></h6>
								      				<p>
		 												<?php echo $listadoVacunasPaciente1['descripcion'] ?> 
										      		</p>
								      			</div>
								      			<div class="col s12 m3 l3">
								      				<h6><b><?php echo $lang_vacunas[16]//Fecha próxima vacuna?>:</b></h6>
								      				<p>
		 												<?php echo $listadoVacunasPaciente1['fechaProximaVacuna'] ?> 
										      		</p>
								      			</div>
								      		</div>
								      		
						      				<div class="row">
						      		
									      		<div class="col s12 m12 l12" style="max-height: 150px; min-height: 150px; overflow-y: scroll;">											      	
											      		
											      		<h6><b><?php echo $lang_vacunas[17]//Observaciones?>:</b></h6>
											      		<p>
			 												<?php echo $listadoVacunasPaciente1['observaciones'] ?> 
											      		</p>
											      	
									      		</div>
									      		
									      	</div><!-- Fin row-->
									      	
										      <br />
						      			
						      			</div>
										
									</li>		
							<?php	
								}//fin foreach
							
							?>
						  	
						  	
						  </ul>
					</div>
				</div>


			 </div>
          </div>
        </div>
      </div>


	<!-- paginacion -->
		<footer class="page-footer white">
					<?php
					
					// render the pagination links
					$pagination->render();
					
					?>
		</footer>	
	<!-- fin paginacion -->	

	
</main>

<script>
	$(document).ready(function () {
		

			$('.datetimepicker').datetimepicker({
				dayOfWeekStart : 1,
				lang:'es',
				timepicker: false,
				mask:true,
				minDate: 0,
				formatDate:'Y/m/d',
				format: 'Y/m/d'
								
			 });
			 
			 var theLanguage = $('html').attr('lang');
			 
			 switch(theLanguage) {
				    case 'Es':
				        $.datetimepicker.setLocale('es');
				        break;
				    case 'En':
				        $.datetimepicker.setLocale('en');
				        break;
				    default:
				        $.datetimepicker.setLocale('es');
				}
			 
		
		
		//funcion para evitar que se salga del sitio y perder los cambios
			window.onbeforeunload = function(e) {
				  e = e || window.event,
				  message = "Seguro que desea salir sin guardar?";
				 
				  // show alert if there are some unsaved form
				  if ($('.unsavedForm').size()) {
				    // For IE and Firefox
				                if (e) {
				                  e.returnValue = message;
				                }
				                // For Safari
				                return message;
				  }
				};
				
				
	});
</script>
