<header>
<!-- Menu web-->
<div class="navbar-fixed teal" style="z-index: 999999 !important;">
     <nav class="teal lighten-2">
        <div class="nav-wrapper" id="nav_wrapper" >
          <a href="<?php echo Config::ruta()?>home/" class="brand-logo" >
            <img class="responsive-img" src="<?php echo Config::ruta()?>Public/img/logos/icon.png" style="max-width: 65%;">
          </a>
          
          
          <a href="#" data-activates="mobile" class="button-collapse"><i class="material-icons">menu</i></a>
          
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li id="menuWebBuscar" ><a href="javascript:void(0)" " ><i class="material-icons left">search</i><?php echo $lang_menu[9] //buscar?></a></li>
            <li id="menuWebNuevo" ><a href="javascript:void(0)"><i class="material-icons left">add_circle</i><?php echo $lang_menu[7] //nuevo?></a></li>
          <!--  <li id="menuWebCuidados" ><a class="dropdown-button" href="#!" data-activates="dropdown_cuidados"><i class="material-icons left">favorite</i><?php echo $lang_menu[8] //cuidados?></a></li>-->
            <li id="menuWebAgenda" ><a href="javascript:void(0)"><i class="material-icons left">event</i><?php echo $lang_menu[3] //agenda?></a></li>
            <li id="menuWebinventario" ><a class="dropdown-button" href="javascript:void(0)" ><i class="material-icons left">widgets</i><?php echo $lang_menu[6] //productos?></a></li>
            <li id="menuWebFacturacion" ><a class="dropdown-button" href="javascript:void(0)" ><i class="material-icons left">attach_money</i><?php echo $lang_menu[24] //registrar?></a></li>
            <li id="menuWebReportes" ><a href="javascript:void(0)"><i class="material-icons left">trending_up</i><?php echo $lang_menu[4] //reportes?></a></li>
            <li id="menuWebListados" ><a href="javascript:void(0)" ><i class="material-icons left">format_list_bulleted</i><?php echo $lang_menu[2] //listados?></a></li>
            <li id="menuWebConfiguracion" ><a class="dropdown-button" href="javascript:void(0)"><i class="material-icons left">settings</i><?php echo $lang_menu[1] //configuracion?></a></li>
            <li id="menuWebUsuario" ><a class="dropdown-button" href="javascript:void(0)" data-activates="dropdown_usuario"><i class="material-icons left">account_circle</i> <?php echo $_SESSION['usuario_nombre']?><i class="material-icons right">arrow_drop_down</i></a></li>
          </ul>
        </div>
      </nav>
  </div>
  
  
  
  


  
  
<!-- Dropdown web-->

<!-- Usuario -->
<ul id="dropdown_usuario" class="dropdown-content">
  <li><a href="javascript:void(0)"><?php echo $lang_menu[10] //perfil?></a></li>
  <li><a href="javascript:void(0)"><?php echo $lang_menu[11] //personalizados?></a></li>
  <!-- <li><a href="#!"><?php echo $lang_menu[12] //preferencias?></a></li>-->
  <!--<li><a href="javascript:void(0)"><?php echo $lang_menu[13] //tutoriales?></a></li>-->
  <li class="divider"></li>
  <li><a href="<?php echo Config::ruta()?>salir/"><?php echo $lang_menu[0] //salir?></a></li>
</ul>


<!-- Dropdown web-->




<!---------- menu mobile ------------------>
<ul class="side-nav" id="mobile">

	 <br />
	 <br />
	 <br />
	 <li><a href="javascript:void(0)"><i class="material-icons">search</i>Buscar</a></li>
      <li><a href="javascript:void(0)"><i class="material-icons">add_circle</i><?php echo $lang_menu[7] //nuevo?></a></li>
     <!--  <li><a class="dropdown-button" href="#!" data-activates="mobile_dropdown_cuidados"><i class="material-icons">favorite</i><?php echo $lang_menu[8] //cuidados?></a></li>-->
      <li><a href="javascript:void(0)"><i class="material-icons">event</i><?php echo $lang_menu[3] //agenda?></a></li>
      <li><a class="dropdown-button" href="javascript:void(0)"><i class="material-icons">widgets</i><?php echo $lang_menu[6] //productos?></a></li>
      <li><a class="dropdown-button" href="javascript:void(0)"><i class="material-icons">attach_money</i><?php echo $lang_menu[24] //facturar?></a></li>
      <li><a href="javascript:void(0)"><i class="material-icons">trending_up</i><?php echo $lang_menu[4] //reportes?></a></li>
      <li><a class="dropdown-button" href="javascript:void(0)"><i class="material-icons">format_list_bulleted</i><?php echo $lang_menu[2] //listados?></a></li>
      <li><a class="dropdown-button" href="javascript:void(0)" ><i class="material-icons">settings</i><?php echo $lang_menu[1] //configuracion?></a></li>
      <li><a class="dropdown-button" href="javascript:void(0)" data-activates="mobile_dropdown_usuario"><i class="material-icons">account_circle</i> <?php echo $_SESSION['usuario_nombre']?><i class="material-icons">arrow_drop_down</i></a></li>
</ul>


<!-- Dropdown mobil-->

<!-- Usuario -->
<ul id="mobile_dropdown_usuario" class="dropdown-content">
  <li><a href="javascript:void(0)"><?php echo $lang_menu[10] //perfil?></a></li>
  <li><a href="javascript:void(0)"><?php echo $lang_menu[11] //personalizados?></a></li>
  <!--<li><a href="#!"><?php echo $lang_menu[12] //preferencias?></a></li>-->
  <li><a href="#!"><?php echo $lang_menu[13] //tutoriales?></a></li>
  <li class="divider"></li>
  <li><a href="<?php echo Config::ruta()?>salir/"><?php echo $lang_menu[0] //salir?></a></li>
</ul>


<!-- Dropdown mobil-->

</header>
