<ul id="slide-out" class="side-nav">
	
   <br />
   <br />
   <br />
   <br />
    <li><a href="<?php echo Config::ruta()?>reportes/gerencial/"><?php echo $lang_reportes[0]//Gerencial?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/citas/"><?php echo $lang_reportes[1]//Citas?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/cirugias/"><?php echo $lang_reportes[2]//Cirugías?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/consultas/"><?php echo $lang_reportes[3]//Consultas?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/desparasitantes/"><?php echo $lang_reportes[4]//Desparasitantes?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/examenes/"><?php echo $lang_reportes[5]//Exámenes?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/formulas/"><?php echo $lang_reportes[6]//Formulas?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/hospitalizaciones/"><?php echo $lang_reportes[7]//Hospitalizaciones?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/inventario/"><?php echo $lang_reportes[8]//Inventario?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/pacientes/"><?php echo $lang_reportes[9]//Pacientes?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/propietarios/"><?php echo $lang_reportes[10]//Propietarios?></a></li>
    <li><a href="<?php echo Config::ruta()?>reportes/vacunas/"><?php echo $lang_reportes[11]//Vacunas?></a></li>
    
</ul>