<ul id="slide-out" class="side-nav">
	
   <br />
   <br />
   <br />
   <br />
    <li><a href="<?php echo Config::ruta()?>personalizados/motivoConsulta/"><?php echo $lang_personalizados[16]//Motivo de consulta?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesConsulta/"><?php echo $lang_personalizados[17]//Observaciones de consulta?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/planConsulta/"><?php echo $lang_personalizados[18]//Plan a seguir en consulta?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesExamenFisico/"><?php echo $lang_personalizados[38] //Observaciones Ex. fisico ?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/motivoCirugia/"><?php echo $lang_personalizados[30] //Motivo de cirugía?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesCirugia/"><?php echo $lang_personalizados[31] //Observaciones de cirugía?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/planCirugia/"><?php echo $lang_personalizados[32]//Plan y cuidados de cirugía ?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesExamen/"><?php echo $lang_personalizados[33]//Observaciones examen?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesFormula/"><?php echo $lang_personalizados[34]//Observaciones Formulación?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/motivoHospitalizacion/"><?php echo $lang_personalizados[35]//Motivo de Hospitalización?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/observacionesHospitalizacion/"><?php echo $lang_personalizados[39]//Obser. de Hospitalización?></a></li>
    <li><a href="<?php echo Config::ruta()?>personalizados/cuidadosAlta/"><?php echo $lang_personalizados[40]//Cuidados alta?></a></li>
    
</ul>