<div class="navbar-fixed">

<nav class="teal lighten-2" role="navigation">
    <div class="nav-wrapper">
        
      <a id="menu_inicio" href="#inicio" data-menuanchor="inicio" class="brand-logo center-align" style="margin-left: 5%;" >
            <img class="responsive-img" src="Public/img/logos/NanuVet.png" style="max-width: 65%;">
      </a>
      
      <ul class="right hide-on-med-and-down" id="menu" >
        <li id="menu_nosotros"><a href="#nosotros" data-menuanchor="nosotros" class="black-text"><i class="fa fa-university left"></i> <?php echo $lang_index[43]//Nosotros?></a></li>
        <li id="menu_tumascota"><a href="#tumascota" data-menuanchor="tumascota" class="black-text "><i class="fa fa-paw left"></i> <?php echo $lang_index[5]//Tu mascota?></a></li>
       <!-- <li id="menu_directorio"><a href="#directorio" data-menuanchor="directorio" class="black-text "><i class="fa fa-map-marker left"></i> Directorio</a></li>-->
        <li id="menu_modulos"><a href="#modulos" data-menuanchor="modulos" class="black-text "><i class="fa fa-cogs left"></i> <?php echo $lang_index[22]//Modulos?></a></li>
        <li id="menu_precios"><a href="#precios" data-menuanchor="precios" class="black-text "><i class="fa fa-usd left"></i> <?php echo $lang_index[44]//Precios?></a></li>
        <li id="menu_contacto"><a href="#contacto" data-menuanchor="contacto" class="black-text "><i class="fa fa-envelope left"></i> <?php echo $lang_index[37]//Contacto?></a></li>
        <li id="menu_login"><a href="#login" data-menuanchor="login" class="black-text "><i class="fa fa-lock left"></i> <?php echo $lang_index[6]//Iniciar sesión?></a></li>
      </ul>

<!-- Movil-->
      <ul id="nav-mobile" class="side-nav">
        <li id="menu_nosotros"><a href="#nosotros" data-menuanchor="nosotros" class="black-text"><?php echo $lang_index[43]//Nosotros?></a></li>
        <li id="menu_tumascota"><a href="#tumascota" data-menuanchor="tumascota" class="black-text "><?php echo $lang_index[5]//Tu mascota?></a></li>
        <!--<li id="menu_directorio"><a href="#directorio" data-menuanchor="directorio" class="black-text ">Directorio</a></li> -->
        <li id="menu_modulos"><a href="#modulos" data-menuanchor="modulos" class="black-text "><?php echo $lang_index[22]//Modulos?></a></li>
        <li id="menu_precios"><a href="#precios" data-menuanchor="precios" class="black-text "><?php echo $lang_index[44]//Precios?></a></li>
        <li id="menu_contacto"><a href="#contacto" data-menuanchor="contacto" class="black-text "><?php echo $lang_index[37]//Contacto?></a></li>
        <li id="menu_login"><a href="#login" data-menuanchor="login" class="black-text "><?php echo $lang_index[6]//Iniciar sesión?></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      
    </div>
  </nav>
  
  
</div>



