<ul id="slide-out" class="side-nav">
	
   <br />
   <br />
   <br />
   <br />
    <li><a href="<?php echo Config::ruta()?>listados/barrios/"><?php echo $lang_menu[18] //Barrios?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/ciudades/"><?php echo $lang_menu[19]//Ciudades?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/categoriasProductos/"><?php echo $lang_menu[32]//Categorías productos?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/desparasitantes/"><?php echo $lang_desparasitantes[0]//Desparasitantes?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/diagnosticosCirugias/"><?php echo $lang_menu[33]//Diagnósticos cirugias?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/diagnosticosConsultas/"><?php echo $lang_menu[34]//Diagnósticos consultas?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/especies/"><?php echo $lang_menu[22]//Especies?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/examenes/"><?php echo $lang_menu[35]//Exámenes?></a></li>    
    <li><a href="<?php echo Config::ruta()?>listados/medicamentos/"><?php echo $lang_medicamentos[0]//Medicamentos?></a></li>  
    <li><a href="<?php echo Config::ruta()?>listados/razas/"><?php echo $lang_menu[23]//Razas?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/servicios/"><?php echo $lang_servicios[0]//Servicios?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/tiposCita/"><?php echo $lang_agenda[0] //Tipos de cita?></a></li>
    <li><a href="<?php echo Config::ruta()?>listados/vacunas/"><?php echo $lang_vacunas[0]//Vacunas?></a></li>
    
</ul>