<main >
	
	 <div class="row">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
	  
              <span class="card-title">
              	<div class="row">
              		<div class="col s6">
              			 <div data-activates="slide-out" class="chip button-collapse" style="cursor: pointer;">
		              		<i class="fa fa-bars" aria-hidden="true"></i>
						    <?php echo $lang_listados[1]//Listas?>				    
						  </div>
              		</div>
              		<div class="col s6 right-align">
              			
              			<i style="cursor: pointer;" data-position="bottom" data-delay="50" data-tooltip="<?php echo $lang_personalizados[44]//Ver tutorial ?>" class="fa fa-play tooltipped" aria-hidden="true" onclick="playVideoTutorial()"></i>

              		</div>
              	</div>
              </span>
              
              
					<div class="row">	
						<div id="div_videoTutorial" style="display: none;" class="col s12 center-align">
								<h5><?php echo $lang_personalizados[27] //Tutorial personalizados?></h5>
							 <video id="videoTutorial_personalizados" class="responsive-video" height="600" width="600"  controls>
							 	
							 	<?php 
							 		
							 		if(is_file("Public/videos/tutoriales/".$idiomaIndex."/listados/listados.mp4")){
							 	
								?>
										<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/listados/listados.mp4" type="video/mp4">
								<?php	
							 		}else{
							 	?>
							 			<source src="<?php echo Config::ruta()?>Public/videos/tutoriales/<?php echo $idiomaIndex ?>/FueraServicio/fueraServicio.mp4" type="video/mp4">
							 	<?php	
							 		}
							 	?>
							 	
							    
							  </video>
							  <h6 class="center-align">
							  	<a class="waves-effect red darken-1 btn" onclick="cerrarVideoTutorial()"><i class="fa fa-stop" aria-hidden="left"></i> <?php echo $lang_personalizados[28] //Cerrar vídeo?></a>
							  </h6>
						</div><!-- Fin div col video-->
					</div>
				
				<div class="row">
					
					<div class="col s12 m12 l12">
						
						<ul class="collection with-header">
							
							<li class="collection-header">
								<h4 id="tituloLi" class="center-align" ><?php echo $lang_desparasitantes[0]//Desparasitantes?>
									<?php
									//saber si tiene permiso para crear desparasitantes
										if(in_array("82", $_SESSION['permisos_usuario'] )){
									?>
						  			<a class="btn-floating waves-effect waves-light teal lighten-2 tooltipped" data-position="right" data-delay="50" data-tooltip="<?php echo $lang_desparasitantes[1]//Nuevo desparasitante?>" onclick="mostrarFormNuevoDesparasitante()">
						  				<i class="material-icons">add</i>
						  			</a>
						  			<?php
						  				}
									?>
						  		</h4>						  		
						  		<br />
						  		<?php
									//saber si tiene permiso para editar desparasitantes
										if(in_array("83", $_SESSION['permisos_usuario'] )){
									?>
						  		<div id="hidden_editarDesparasitante" style="display: none ;">						  			
						  			
						  			<div class="row">
				                      	<div class="col s12 m12 l12">
				                      		<h4 class="center-align"><?php echo $lang_desparasitantes[2]//Editar desparasitante?></h4>
				                      	</div>
				                      </div>
						  			<div class="row">
						  				<form id="form_editarDesparasitante" name="form_editarDesparasitante" action="" method="post" >
						  					<input type="hidden" id="idEditarDesparasitante" name="idEditarDesparasitante" value="" />
						  					<input type="hidden" id="replicaNombre" name="replicaNombre" value="" />
							  				<div class="input-field col s12 m4 l4">
							  					<input type="text" id="editarNombreDesparasitante" name="editarNombreDesparasitante" value="" length="100" maxlength="100"/>
							  					<label id="label_editarNombreDesparasitante" for="editarNombreDesparasitante"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_desparasitantes[3]//Nombre desparasitante?></label>
							  				</div>
							  				
							  				<div class="input-field col s12 m8 l8">
							  					<input type="text" id="editarDescripcionDesparasitante" name="editarDescripcionDesparasitante" value="" length="200" maxlength="200"/>
							  					<label id="label_editarDescripcionDesparasitante" for="editarDescripcionDesparasitante"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_desparasitantes[4]//Descripción?></label>
							  				</div>
							  				
						  				</form>
						  				<div class="input-field col s12 m12 l12 right-align">					  					
						  						<a class="waves-effect red darken-1 btn" onclick="cancelarEdicionDesparasitante()" ><?php echo $lang_botones[5]//Cancelar?></a>		
						  						<a class="waves-effect waves-light btn" onclick="comprobarEdicionDesparasitante()" ><?php echo $lang_botones[4]//Editar?></a>				  									  					
						  				</div>
						  			</div>
						  			
						  		</div>
						  		<?php
						  		
									}//fin permiso editar desparasitante
									
									//saber si tiene permiso para crear desparasitantes
										if(in_array("82", $_SESSION['permisos_usuario'] )){
									?>
						  		<div id="hidden_NuevoDesparasitante" style="display: none;">
						  			
						  			<div class="row">
						  				<form class="col s12 m12 l12" id="form_nuevoDesparasitante" name="form_nuevoDesparasitante" action="" method="post">
						  					
						                    <input type="hidden" id="envioNuevoDesparasitante" name="envioNuevoDesparasitante"  value="envio"/>
						                    
						                    <div class="row">
                          
						                      
						                      <div class="input-field col s12 m4 l4">						                            
						                            <input id="nombreDesparasitante" name="nombreDesparasitante" type="text" class="validate" length="100" maxlength="100">
						                            <label id="label_nombreDesparasitante" for="nombreDesparasitante"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_desparasitantes[5]//Nombre del nuevo desparasitante?></label> 
						                      </div> 
						                      
						                      <div class="input-field col s12 m8 l8">						                            
						                           <input id="descripcionDesparasitante" name="descripcionDesparasitante" type="text" class="validate" length="200" maxlength="200">
						                           <label id="label_descripcionDesparasitante" for="descripcionDesparasitante"   data-error="<?php echo $lang_error[0]//Debe completar este campo?>" data-success="<?php echo $lang_error[1]//Ok?>" style="width:95%; text-align: left;" ><?php echo $lang_desparasitantes[4]//Descripción?></label>
						                      </div> 
						                      
						                  </div><!-- fin row-->
						                  
						                  <div class="input-field col s12 m12 l12 right-align">
						                  	<a class="waves-effect red darken-1 btn" onclick="cancelarGuardadoNuevoDesparasitante()"><?php echo $lang_botones[5]//Cancelar?></a>
						                    <a class="waves-effect waves-light btn" onclick="validarGuardadoNuevoDesparasitante()"><?php echo $lang_botones[2]//Guardar?></a>
						                  </div><!-- fin row-->
						  					
						  					
						  				</form>
						  			</div><!-- Fin row-->
						  		</div><!-- fin Div oculto para formulario del nuevo desparasitante-->
						  		<?php
						  			}//fin permiso crear desparatiante
						  		?>
						  		
							</li>
							
						</ul>
						
					</div>				
					
				</div><!-- Fin row-->
				
				
				<div class="row">
					<div class="input-field col s10 m3 l3">
						<i class="fa fa-search prefix" aria-hidden="true"></i>
						<input placeholder="<?php echo $lang_desparasitantes[6]//Buscar desparasitante (Escribe y selecciona)?>" id="buscarDesparasitante" type="text" class="validate" onkeypress="buscarDesparasitanteListados()" >
						<input type="hidden" id="idDesparasitanteBuscada" value="" />
					</div>
					<div class="input-field col s2 m2 l2">
						<i id="btnCancelarBusqueda" class="fa fa-times-circle fa-3x" aria-hidden="true" style="cursor: pointer; display: none;" onclick="cerrarBusquedaDesparasitante()"></i>
					</div>
				</div>
				
				
				<div class="row">
					
					<div class="col s12 m12 l12">
						<span id="spanActivar" style="display: none;"><?php echo $lang_desparasitantes[7]//Activar desparasitante?></span>
						<span id="spanDesactivar" style="display: none;"><?php echo $lang_desparasitantes[8]//Desactivar desparasitante?></span>
						
							<div id="resultadoDesparasitantesAjax">
								
							</div><!-- Fin para el resultado de los desparasitantes ajax-->
							
							<div id="resultadoDesparasitantes">
								<table class="bordered highlight centered responsive-table">
									
									<thead>
										<tr>
											<th><?php echo $lang_desparasitantes[9]//Desparasitante?></th>
											<th><?php echo $lang_desparasitantes[4]//Descripción?></th>
											<th><?php echo $lang_general[12]//Estado?></th>
										</tr>
									</thead>
									
									<tbody>
										
										<?php									
											foreach ($listadoDesparasitantes as $listadoDesparasitantes1) {
												
												if($listadoDesparasitantes1['estado'] == 'A'){																																																			//Desactivar desparasitante
													$btn = '<span id="spanB_'.$listadoDesparasitantes1['idDesparasitante'].'"> <a id="'.$listadoDesparasitantes1['idDesparasitante'].'" class="waves-effect waves-light btn tooltipped" onclick="desactivarDesparasitante(this.id)"  data-position="right" data-delay="50" data-tooltip="'.$lang_desparasitantes[8].'" ><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}else{																																																											//Activar desparasitante
													$btn = '<span id="spanB_'.$listadoDesparasitantes1['idDesparasitante'].'"> <a id="'.$listadoDesparasitantes1['idDesparasitante'].'" class="waves-effect red darken-1 btn tooltipped" onclick="activarDesparasitante(this.id)" data-position="right" data-delay="50" data-tooltip="'.$lang_desparasitantes[7].'"><i class="fa fa-power-off fa-2x" aria-hidden="true"></i></a></span>';
												}
												
												$parametros = "'".$listadoDesparasitantes1['idDesparasitante']."','".$listadoDesparasitantes1['nombre']."','".$listadoDesparasitantes1['descripcion']."'";
										?>
										
											<tr style="cursor: pointer;">
												<td <?php if(in_array("83", $_SESSION['permisos_usuario'] )){ ?> onclick="editarDesparasitante(<?php echo $parametros?>)" <?php } ?> ><?php echo $listadoDesparasitantes1['nombre']?></td>
												<td <?php if(in_array("83", $_SESSION['permisos_usuario'] )){ ?>  onclick="editarDesparasitante(<?php echo $parametros?>)" <?php } ?>><?php echo $listadoDesparasitantes1['descripcion']?></td>
												<td>
													<?php echo $btn ?>											
												</td>
											</tr>											
												
										<?php		
											}//fin foreach								
										?>
										
										
										
									</tbody>
									
									
								</table>
								
							</div><!-- Fin div para los resultados de los desparasitantes-->	
						
					</div>
					
				</div><!-- Fin row-->
				
				

			 </div>
          </div>
        </div>
      </div>


	<!-- paginacion -->
		<footer class="page-footer white">
					<?php
					
					// render the pagination links
					$pagination->render();
					
					?>
		</footer>	
	<!-- fin paginacion -->	
	
</main>